# Tu là cầu bình an hay sửa đổi xấu thành tốt? {- #cau-binh-an-hay-sua-doi}

Trong giới Phật tử chúng ta ngày nay đa số không hiểu rõ ý nghĩa chữ TU, nên ứng dụng sai lầm một cách đáng thương. Khi đến chùa xin qui y, họ thầm nghĩ từ đây về sau được Phật hộ độ cho mình khỏe mạnh, gia đình mình an ổn, mọi mong cầu được như ý, khi chết được Phật rước về cõi Phật... Chớ họ không hiểu rằng, kể từ ngày qui y Tam Bảo là tự mình quyết tâm chừa bỏ những thói hư tật xấu, mình quyết thắng mọi tâm niệm, hành động đê hèn ác độc của mình, và mình cố gắng tạo dựng đầy đủ phước lành để chết được sanh về cõi Phật. Họ đinh ninh trong lòng TU là nương tựa Tam Bảo, là van xin với Phật, là thỏa mãn mọi mong cầu, là an lành suốt cuộc đời..., nên trở thành yếu hèn ỷ lại, mất hết ý nghĩa chữ TU.

Bởi bản chất con người hầu hết là yếu hèn, sợ hãi, tham lam, nên bước chân vào đường tu, họ thích ỷ lại, van xin và mong cầu. Do đó làm biến thái tinh thần tu hành của người Phật tử.

**Yếu hèn**  
  
Phát xuất từ tư tưởng yếu hèn, nên khi qui y Tam Bảo, Phật tử này chỉ một bề trông cậy gởi gấm đời sống của mình và gia đình mình cho Phật, mọi việc đều nhờ Phật hộ độ khi sống được bình an, lúc chết được Phật rước về cõi Phật. Với tâm niệm này, Phật tử cứ tưởng tu là thường đi chùa lễ Phật, thường cúng dường, thường cầu nguyện là tròn bổn phận người tu. Những người này cung kính Phật như một vị thần hộ mạng, tưởng như Phật đủ quyền năng bảo hộ cho bản thân và gia đình họ suốt đời. Vì thế, khi bản thân hay gia đình xảy ra tai ách gì, họ tha thiết chí thành cầu Phật gia hộ cho tai qua nạn khỏi. Nếu cầu nguyện Phật không được kết quả, nghe ở đâu có cậu đồng hay bà bóng giỏi, hoặc ông thần nào linh thiêng cầu gì cũng được như nguyện, họ liền mang hương đèn đến đó cầu xin. Bởi đến với Phật bằng tâm ỷ lại, trông cậy, nên khi trông cậy không được toại nguyện thì họ bước sang nơi khác một cách dễ dàng.

**Sợ hãi**  

Khi gặp tai nạn, người ta không biết tìm nơi nào ẩn náu cho được an ổn, nghe ai giới thiệu qui y với Phật sẽ được bình an, họ liền đến xin qui y Tam Bảo. Họ cứ nghĩ qui y Phật sẽ được Phật che chở, cứu độ cho qua hết tai nạn. Vì thế, họ chỉ biết tu là van xin, cầu khẩn, chí thành khấn vái là tu. Mỗi đêm họ thắp hương lễ Phật, cầu nguyện Phật gia hộ cho họ được mọi thứ an bình. Trong gia đình khi có người bệnh, hoặc xảy ra tai nạn, họ thắp hương quì trước bàn Phật tha thiết van xin Phật cứu bệnh giải ách. Nếu van xin được kết quả tốt, họ tăng trưởng lòng tin Tam Bảo. Bằng trái lại, họ mất lòng tin Phật, vì Phật không linh ứng như sở cầu. Ðược nghe nơi nào linh thiêng xin gì được nấy , họ liền từ giã đạo Phật để sang nơi ấy cầu xin. Do họ đến với Phật bằng tâm niệm sợ hãi, nên đời tu của họ chỉ cầu được bình an. Nếu không được bình an, họ sẽ chạy tìm nơi khác để ẩn nấp.

**Tham lam**
  
Do lòng tham sâu đậm, nên khi qui y Phật họ vẫn một bề mong cầu cho thỏa mãn lòng tham. Ðến chùa không phải để học đạo tu hành, mà để cầu xin. Chỉ cần cúng Phật một bó nhang, một dĩa quả, họ lại xin Phật đến trăm ngàn thứ. Nào là xin Phật cho gia đình bình an, xin cho con cái thi đậu, xin cho làm ăn phát tài, xin cho tai qua nạn khỏi, xin cho thân nhân quá cố được siêu sinh Tịnh Ðộ v.v. và v.v. Họ chi ra cúng Phật quá ít, mà họ xin lại quá nhiều. Nếu xin được như ý thì họ tinh tấn đi chùa, còn xin không được thì họ tìm chỗ nào linh thiêng hơn để đến cầu xin cho thỏa mãn.

Bởi những người Phật tử như thế đến với chùa, nên trong chùa mới có xin xăm bói quẻ, cúng sao cúng hạn, coi ngày lành ngày dữ... để thỏa mãn đòi hỏi của họ. Mặc dù gần đây Giáo hội Phật giáo Việt Nam kêu gọi dẹp bỏ mê tín dị đoan, song thói quen của những Phật tử này vẫn chưa bỏ được. Nguyên nhân Phật giáo suy đồi phần lớn do những vị này mà ra. Là Phật tử mà họ không tin nhân quả, không hiểu Phật là gì, không biết tu như thế nào, làm sao không tạo thành những điều kiện u tối cho Phật giáo? Ðây là những tệ nạn do các Phật tử quan niệm tu Phật để *"cầu được bình an"*.

Nếu người hiểu rõ *"Tu là sửa đổi xấu xa thành hay tốt"* thì không có quan niệm như trên. Mục đích họ đến qui y Tam Bảo cốt nương chánh pháp để tu hành trừ sạch bệnh tham sân si phiền não của mình. Phật thường dạy, Ngài *"theo bệnh cho thuốc để trừ bệnh khổ cho chúng sanh"*. Nơi nội tâm chúng ta có bệnh gì thì Phật có thứ thuốc ấy để trị lành bệnh. Cho nên nói *"chúng sanh có vô lượng phiền não, Phật có vô lượng pháp môn"*. Vì thế, tu là dùng Phật pháp chuyển hóa tâm niệm sai lầm, xấu xa, tội ác của chúng ta. Biết vậy thì tu là phải học hỏi giáo pháp và ứng dụng giáo pháp để trị lành những tâm bệnh của mình. Học hỏi giáo pháp là mở sáng con mắt trí tuệ, là đi lần trên con đường giác ngộ, tức là tu theo đạo Phật. Vì Phật là con người giác ngộ, đạo Phật là con đường tiến đến giác ngộ. Mọi khổ đau của chúng sanh do si mê tạo nên, muốn giải thoát khổ đau là phải giác ngộ. Tuy nhiên giác ngộ mức độ cao thấp khác nhau, tùy đó mà con người được bớt khổ hay hết khổ. Học hỏi giáo pháp là học Phật, ứng dụng giáo pháp để tu hành là tu Phật. Với tinh thần tu học này, chúng ta không tìm đâu thấy có ỷ lại, van xin, cầu cúng; mà thấy mỗi người trang bị sẵn ngọn đuốc trí tuệ của mình để mồi với ngọn đuốc chánh pháp của Phật. Những người này không có yếu hèn, sợ hãi, tham lam; mà lòng cương quyết, can đảm, kiên trì tự nỗ lực tu hành cho đến ngày giải thoát. Tham sân si là mục tiêu họ phải chiến đấu đến bao giờ tiêu diệt hết mới thôi. Bởi vậy một bước tiến tu là một niềm an lạc, càng tu khổ đau càng tan rã, như tuyết giá tan rã khi ánh mặt trời lên. Tiến tu như thế, có lý do gì thối tâm bỏ đạo, có duyên cớ nào phải lùi bước đi theo đường tà?

Ðược nhiều người tin Phật, chưa hẳn Phật giáo đã thịnh. Nếu tin theo lối ỷ lại, van xin, cầu cúng, dù có bao nhiêu triệu người, Phật giáo vẫn bị chìm trong u tối. Vì mê tín thì không giác, không giác thì có dính dáng gì với đạo Phật? Chúng ta thực tâm tu theo đạo Phật thì cố mở sáng con mắt trí tuệ, nhận chân những sự thật qua lời dạy của đức Phật. Như Phật dạy: *"các pháp là vô thường"*, chúng ta phải chiêm nghiệm lý này cho tường tận, thấu suốt tường tận chúng ta mới nếm được pháp vị *"vô thường"* của Phật ban cho. Ðạo lý *"nhân quả"* là nền tảng của Phật giáo, nếu chúng ta không suy tư cho thấu đáo thì lòng chánh tín khó phát sanh. Phật dạy *"tin nhân quả là chánh tín"*, nếu chúng ta không chịu khó rà đi soát lại kỹ càng thì làm sao đủ lòng tin nhân quả. Bởi không tin nhân quả, chúng ta dễ sanh yếu hèn, sợ hãi, van xin rơi vào đường mê tín. Lý *"nhân duyên"* là chân lý của muôn pháp, nếu không nghiền ngẫm thật chín chắn, thật nhuần nhuyễn, chúng ta không thể hiểu nổi chỗ thâm áo của nó. Ðã không hiểu lý *"nhân duyên"* chúng ta làm sao thấy được chỗ cao siêu của Phật giáo mà sanh lòng tin kính?

Muốn hưởng được pháp vị một cách thấm thía nồng nàn, người Phật tử phải tận lực suy tư nghiền ngẫm chánh pháp thật tường tận tinh vi. Như muốn thưởng thức hương vị của thức ăn thật đầy đủ, người ta phải nhai thật nhuyễn những thức ăn ấy. Ðồng thời Phật tử phải ứng dụng triệt để chánh pháp trong cuộc sống hằng ngày. Mọi người ai cũng thừa nhận nơi nội tâm của mình đã sẵn có tính lương thiện và tính tội ác. Tội ác là nhân khổ đau cho mình và cho người, đời này và đời sau, nó làm cho con người trở thành hèn hạ xấu xa. Lương thiện là nhân an vui cho mình cho người, đời này và nhiều đời khác, nó gầy dựng cho con người trở thành bậc Hiền, Thánh. Nếu muốn hết khổ được vui, chúng ta phải dẹp bỏ tính tội ác, nuôi dưỡng tính lương thiện, chính đây là tu. Tu là điều kiện tất yếu của mọi người, không riêng ai và giới nào, nếu là người muốn hết khổ được vui và cố vươn lên bậc Hiền, Thánh.

Ước mong các Phật tử tự kiểm điểm lại xem, mình thuộc hạng nào trong hai hạng trên. Nếu là hạng đến với Phật để *"cầu bình an"* thì nên chuyển hướng can đảm vươn lên để thành Phật tử chân chánh, không thối chuyển trên đường đạo. Nếu là hạng đến với Phật để *"sửa đổi xấu thành tốt"* thì cố gắng hơn nữa để mọi xấu xa đều dứt sạch, mọi khổ đau đều tan biến, tự tại tiến thẳng trên đường giác ngộ. Toàn thể Phật tử đều là người chánh tín, biết ứng dụng chánh pháp chuyển hóa ba nghiệp của mình trở thành con người thuần thiện, thì Phật giáo mới thực sự là ngọn đuốc sáng soi đường cho chúng sanh ra khỏi đêm tối vô minh.
