# Nguồn gốc mê tín {- #nguon-goc-me-tin}

Mê tín là cái bệnh những nhà trí thức đều chê trách, Chánh quyền cũng chủ trương dẹp trừ mê tín. Thế mà bệnh mê tín mỗi ngày một tăng, càng lúc càng lan rộng. Thậm chí có những nước tự cho mình là văn minh nhất thế giới, mà dân chúng trong nước ấy vẫn còn mê tín. Ðó là tại sao? Trước tiên chúng ta phải biết mê tín là thế nào? Mê tín là lòng tin mù quáng không thấy lẽ thật, không đúng chân lý. Ðơn cử một số thí dụ để chúng ta biết rõ. Như tin ông đồng bà cốt, tin xin xăm bói quẻ, tin ngày lành ngày dữ, tin số mạng sang hèn, tin coi tay xem tướng, tin cúng sao cúng hạn, tin thầy bùa thầy chú, tin cầu cúng tai qua nạn khỏi v.v... Những lối tin này không có lý luận, không đủ bằng chứng, không có lợi ích, nên gọi là mê tín.

## Nguồn gốc mê tín {- #nguon-goc}

Mê tín không phải là sự ngẫu nhiên phát sanh mà có nguồn gốc phát xuất cụ thể. Có hai thứ nguồn gốc mê tín:

### Mê tín do tâm mong cầu {- #do-tam-mong-cau}

Con người khi mong cầu một điều gì mà quá khả năng mình thì dễ sanh mê tín. Ví như có người muốn vay một số vốn lớn làm ăn, không biết việc làm ăn này sẽ kết quả tốt hay xấu. Tự nhiên lòng họ thấy băn khoăn lo lắng không biết hỏi ai, tin ai. Nghe nói ông đồng bà cốt nào đó linh ứng nói quá khứ vị lai rất trúng, họ liền muốn tìm tới hỏi han. Chỉ tốn tiền quẻ có năm bảy trăm, mà biết được việc làm ăn của mình thành công hay thất bại thì an ổn biết mấy. Hoặc trên đường công danh có những học sinh, sinh viên sắp đến kỳ thi cử, lo âu thân phận mình không biết thi đậu hay rớt. Nghe đồn lăng này, miếu kia linh hiển xin xăm bói quẻ sẽ báo đúng những điều sắp đến, các cô các cậu không đủ lòng tin vào khả năng học hành của mình, nhất định đi đến lễ bái xin xăm để hỏi thăm thần thánh xem thế nào. Hoặc có những người muốn ra ứng cử chức này ghế nọ, mà không biết số phận của mình là đỏ hay đen, lòng họ bồn chồn bất an. Có người giới thiệu ông A đổ số tử vi rất hay, xem số biết vận mạng người đúng một trăm phần trăm *(100%)*, ông ta ngại gì không đến đó để xem thử mình có số công danh hay không. Còn lắm trường hợp tương tự như thế không thể kể hết, đại để chỉ vì mong cầu mà không tin sức mình nên sanh ra mê tín.

### Mê tín do tâm sợ hãi {- #do-so-hai}

Sợ hãi là gốc sanh ra mọi mê tín. Một gia đình nọ tiếp tục xảy ra đôi ba người chết *"bất đắc kỳ tử"*, những người còn lại đâm ra hoảng hốt, nghe đâu có thầy bùa hay thầy chú giỏi liền đi rước về ếm đối để mình khỏi bị chết trùng. Chính vì sợ hãi mà những người này sanh mê tín. Có những người bị tai nạn dồn dập, vừa té xe bị thương lại bị người giựt nợ, con trai thi rớt, con gái bị bệnh... mất bình tĩnh, nghe ông đồng này hay bà cốt kia giỏi, họ liền tìm đến để cầu cứu hộ, xin phép lạ về để trừ tai ách. Lại có người sắp làm điều mạo hiểm, lo sợ không biết có thể vượt qua mọi nguy hiểm được chăng, họ vào am vào miếu để thưa hỏi thần linh bằng cách rút xăm, bói quẻ. Nếu rút được xăm  tốt quẻ lành thì họ mới mạnh dạn xông pha. Có những người mắc phải bệnh nan y, họ buồn khổ sợ chết. Nghe bất cứ nơi đâu có sự linh thiêng mầu nhiệm, họ đều đi đến để xin thuốc cầu bùa. Dù phải làm những điều quái dị, họ thảy đều chấp nhận, miễn sao lành bệnh là vui. Hoặc có người sợ vận xui hạn xấu, nên đầu năm đến chùa cúng sao cúng hạn, cầu cho tròn năm cuộc sống được hanh thông, gia đình được an vui may mắn. Hoặc có những người vì thương cha mẹ đã quá cố, sợ cha mẹ chết rơi vào địa ngục chịu đói khổ nhọc nhằn, họ bèn nhờ thầy cúng dán lầu kho, xe cộ, giấy tiền vàng bạc, lễ cúng đốt xuống cho cha mẹ được an hưởng nơi âm ti... Mọi sự sợ hãi đều là cội nguồn của mê tín. Là con người có ai không mong cầu, không sợ hãi, đã có hai thứ này thì nhất định sẽ rơi vào mê tín dị đoan. Khi chưa gặp việc, chúng ta chống đối mê tín, nhưng gặp lúc có việc khắc khoải mong cầu, kinh hoàng sợ hãi, chúng ta cũng trở thành mê tín như ai. Dù là người có cấp bằng cao, có kiến thức rộng, nếu trong tâm có mong cầu sợ hãi, họ cũng sẽ rơi vào hố mê tín. Có những người đứng trước quần chúng thì miệt thị chê bai kẻ mê tín, song về nhà gặp lúc gia cảnh rối nùi bà xã vẫn đi bói quẻ xin xăm, hỏi quá khứ vị lai nơi ông đồng bà cốt. Bởi con người mang sẵn tính tham lam, thói hèn nhát, nên khi muốn thỏa mãn sự mong cầu, muốn được bình an khi nguy hiểm, đều nảy sanh mê tín dị đoan. Thế nên mê tín dị đoan là bệnh bẩm sanh có sẵn nơi mọi con người. Muốn chữa lành bệnh này phải là bậc Thánh y và thần dược mới mong cầu điều trị được.

## Pháp Phật dạy trị bệnh mê tín {- #tri-benh-me-tin}

Phật là bậc Thánh y, pháp của Phật dạy là thần dược, nếu ai tin nơi Phật, dùng thuốc Phật dạy trị bệnh mê tín chắc chắn sẽ được lành. Pháp Phật dạy trị bệnh mê tín có hai thứ:

### Nhân quả {- #nhan-qua}

Nhân quả là sự thật, là lý đương nhiên mà người đời ít ai nghĩ đến. Bởi con người cố mong cầu cái quả mà không cân xứng cái nhân. Hoặc họ ước mơ nhặt được những cái quả ngoài tầm tay của họ. Hoặc họ không có tâm tự tín nên làm việc gì cũng ngờ vực lo âu. Ðó là những lý do khiến họ đâm ra mê tín. Nếu con người tự biết rõ rằng mọi hậu quả nên hư tốt xấu, thành công thất bại đều do nguyên nhân hay dở đủ thiếu của con người tạo nên. Không có cái quả nào từ trên trời rơi xuống, hoặc dưới đất bỗng dưng hiện lên, mà đều do trí sáng suốt và sức lao động cần cù của con người tạo ra. Chúng ta cứ tạo nhân tốt thật đầy đủ thì quả tốt nhất định đến. Ví như chúng ta muốn có quả một cây cam mật, trước chúng ta phải chọn giống từ quả cam mật, hoặc chiết cành từ cây cam mật. Kế đó, chúng ta phải lựa chỗ đất mầu mỡ ương giống xuống, rồi tưới nước bón phân đúng thời đúng lúc, chăm sóc sâu bọ đừng cho phá hại. Sau này chúng ta sẽ thu hoạch được quả cam mật không sai. Chúng ta khỏi phải mong cầu, khỏi phải trông đợi, mà quả sẽ thành tựu viên mãn theo sở nguyện của mình. Cũng thế, mọi sự nên hư thành bại trong đời mình không phải ngẫu nhiên mà đến, không phải từ ai ban cho, mà do những cái nhân chúng ta tạo từ trước, khi nhân duyên đầy đủ thì quả thành. Không phải chúng ta cầu xin mà nó đến, không phải chúng ta xua đuổi mà nó đi, một khi nhân đã thành thì quả phải chịu. Chúng ta cứ sợ tai ương đổ lên đầu chúng ta, mà lại không sợ những nhân xấu do mình đã gieo từ trước. Chúng ta cầu thần khấn Phật ban bố phúc lành cho chúng ta, mà chúng ta không chịu ban ơn bố đức cho những người chung quanh mình. Những nhân xấu kết hợp thành quả xấu, những nhân tốt tụ hội thành quả tốt. Cầu mong quả tốt mà không chịu gieo nhân tốt, sợ hãi quả xấu mà không dừng tay tạo nhân xấu, sự cầu mong sợ hãi ấy chỉ là việc không đâu. Chi bằng chúng ta hằng ngày cứ tạo nhân lành, tránh nhân dữ, chả cần cầu mong sợ hãi chi vô ích.

Song nhân quả không phải đơn thuần mà đa dạng, chẳng phải chỉ do trực tiếp ở hiện tại mà lại gián tiếp của nhiều đời. Biết rõ nhân quả tự mình gây tạo, chúng ta can đảm nhận những quả khổ mà không chút sợ hãi buồn phiền. Mình làm chủ tạo nhân, chính mình làm chủ thọ quả, còn cầu xin cái gì, cần hỏi han ai nữa. Chỉ mình sáng suốt khi tạo nhân, cần cù nuôi dưỡng bảo vệ cho nhân tăng trưởng, thì quả chín mọng sẽ đến tay mình một cách dễ dàng. Chúng ta tin chắc lý nhân quả như thế, mọi mê tín sẽ tan theo mây khói. Ðấy là quyền con người sẽ nằm gọn trong bàn tay của chúng ta.

### Ba cửa giải thoát *(Tam giải thoát môn)* {- #ba-cua-giai-thoat}

Ba cửa này là Không, Vô tướng, Vô nguyện *(Vô tác)*. Ðây là người tu Phật được trí tuệ thâm hậu, thấy thấu suốt con người và ngoại cảnh đúng như thật. *"Không"* là từ con người cho đến muôn vật đều do nhân duyên kết hợp thành, không có chủ thể nhất định. Bởi căn cứ trên lý nhân duyên, thấy vạn vật không có chủ thể nên nói là *"Không"*. Từ một cái nhà cho đến cái bàn cái ghế, cây bút chì... tìm thử cái gì là chủ thể của nó. Nếu có chủ thể thì không đợi duyên hợp, đợi duyên hợp mới có thì nhất định không có chủ thể. Ðến con người chúng ta thử tìm xem cái gì là chủ thể của thân này? Như Phật dạy thân này do tứ đại *(đất, nước, gió, lửa)* hợp thành, thiếu một trong bốn thứ thì thân phải hoại. Ðã là bốn thứ thì thứ nào là chủ? Có một thứ làm chủ thì thiếu một thứ khác tại sao nó không còn? Bốn thứ này lại thù địch chống đối nhau, đem bốn đứa thù nhốt chung một chỗ thì có an ổn không? Chúng ta có bổn phận phải nuôi dưỡng điều hòa bốn kẻ thù này, bằng cách chọn những thức ăn uống nào để quân bình chúng. Về tinh thần cũng thế, nội tâm chúng ta có mặt tốt xấu thiện ác đủ thứ, thử hỏi cái nào là chủ? Cho nên nói là đời sống của ta, mà thực sự cái gì là ta? Cái ta chỉ là tưởng tượng chớ không có thực thể. Từ lãnh vực không có thực thể nhìn sang lãnh vực *"Vô tướng"* thực hợp lý vô cùng. Bởi vì vạn vật không có thực thể nên không có tướng thật *(vô tướng)* của nó. Cái mà chúng ta trông thấy, sờ mó được chỉ là giả tướng của duyên hợp mà thôi. Người, vật chỉ là tướng hư giả. Ðã là hư giả chúng ta có mong cầu để được, sợ hãi khi mất hay không? Thế là tiến đến *"Vô nguyện"*. Bởi thấy thân hư dối, mọi vật hư dối, chúng ta không còn tham sống sợ chết, không còn đam mê vàng ngọc. Ðã thấy trên thế gian này không có cái gì đáng mong cầu, đáng sợ hãi, thì còn gì phải khấn nguyền, phải van xin, phải thưa hỏi các vị thánh thần. Dùng trí tuệ này dẹp tan mê tín, như chế nước sôi trên băng. Ba cửa giải thoát này là đỉnh cao của trí tuệ, thấy tận cùng bản chất con người *(ngã)* và vạn vật *(pháp)*. Chính do thấy rõ bản chất hư dối của chúng, nên gỡ bỏ mọi mê lầm cố chấp, mọi tham lam trói buộc, được tự tại an vui, gọi là giải thoát.

Tóm lại, mê tín là một tệ nạn của xã hội, nó tạo dựng những con người yếu hèn, mất tự tin, không sáng suốt. Muốn có một xã hội văn minh lành mạnh, chúng ta không thể nào chấp nhận nạn mê tín hoành hành. Huống nữa, trong giới Phật giáo chúng ta đang kế thừa chánh pháp giác ngộ giải thoát của đức Thế Tôn, mà nuôi dưỡng chấp nhận mê tín được sao? Thế mà có nhiều Tăng sĩ trụ trì, khi nghe Phật tử than làm ăn sa sút, liền bảo đến chùa Thầy cầu nguyện cho; nghe con cháu Phật tử sắp thi cử, bảo ghi tên để Thầy cầu nguyện cho; nghe Phật tử than gia đình xảy ra tai nạn, bảo đến chùa Thầy cúng sao cúng hạn cho... Ôi thôi vô số chuyện, cái gì thầy cũng lãnh hết, lo hết và bao thầu hết. Ðó là chúng ta đang truyền đăng tục diệm, hay chúng ta dụi tắt ngọn đuốc chánh pháp của đức Như Lai?
