# Tình thương sẽ không còn khi người ta cần ngon miệng {- #tinh-thuong-khong-con-khi-can-ngon-mieng}

Tình thương là cây linh dược trị lành mọi bệnh khổ của chúng sanh. Vậy mà, con người nỡ đang tay bẻ cành chặt nhánh khiến nó sắp lụi tàn. Cũng may! Nó còn sót lại vài cành già và đang nẩy ít chồi non. Mong rằng nhân loại nhận thức được giá trị tuyệt vời của nó, ra công bảo vệ, vun tưới cho nó phát triển sum sê, thật là hạnh phúc vô vàn của nhân loại. Vô tình hay cố ý, chúng ta phá hoại cho cây linh dược tàn lụi đi, đây là một mất mát lớn lao của nhân loại, không có gì bù đắp được.

Chú Ba nhà ở gần chùa, chú nuôi một con gà mái, đẻ được một đàn gà con. Ðàn gà con mỗi con đều tròn trịa dễ thương. Sáng nào chú cũng hốt một nắm gạo ra đứng trước sân kêu *"túc, túc"*, gà mẹ dẫn đàn gà con chạy ùa ra vây quanh chú, mổ những hạt gạo do chủ rải, chúng nuốt ngon lành. Chú nhìn đàn gà con có vẻ trìu mến. Có lẽ đàn gà con cũng nhìn chú là ông chủ quí kính đang yêu thương nuôi dưỡng chúng. Tình của chú Ba và đàn gà con càng ngày càng sâu đậm hơn. Trải mấy tháng sau, đàn gà con đã lớn thành gà giò *(gà vừa ăn thịt)*. Hôm nay nhà chú Ba có khách, cũng như mọi hôm, sáng chú nắm gạo ra giữa sân đứng kêu *"túc, túc"*, đàn gà chạy lại bu quanh chú, vừa bỏ gạo chúng ăn chú vừa chụp lấy một con. Con gà bị chụp la hoảng lên, đàn gà còn lại chạy tứ tán. Tiếng la thất thanh của con gà không làm động tâm chú chút nào. Sau đó, nó còn bị cột chân, và cuối cùng lôi ra cắt cổ. Tiếng la cứu mạng và gắng sức vùng vẫy đành đạch để thoát chết của con gà, không làm sao lay chuyển được ý định của chú. Thế là xong một đời của con gà, để làm mồi ngon cho người chủ mến thương trước kia. Tình thương của chú Ba đối với đàn gà con, chỉ có khi chưa cần làm thức ăn ngon miệng. Ðến khi cần thịt gà làm thức ăn, thì tình thương ấy liền biến đi như mây khói!

Ở chùa có nuôi hai con chó, một con tên Tiểu Hỷ, một con tên Tu Tu. Sáng nào hai con cũng vật lộn nhau ành ạch ở trước sân, hai đứa săn đuổi nhau, đè cắn cạp nhau một cách thân tình. Mỗi khi trông thấy hai đứa đùa giỡn nhau, tôi cũng vui lây. Dù là súc sanh, chúng cũng biết vui đùa, cũng biết thân yêu nhau như con người nào khác. Song, khi thằng Tiểu Hỷ được quí Cô cho một tô cơm, đang ăn ngon lành, thằng Tu Tu chạy đến gần, thằng Tiểu Hỷ liền nhe răng hầm hừ, thằng Tu Tu đành lấm lét tránh xa. Ngược lại cũng thế, khi thằng Tu Tu đang ăn, thằng Tiểu Hỷ lại gần, cũng bị thằng Tu Tu nhe răng hầm hừ. Sau bữa ăn chúng cũng vui vẻ chơi lại với nhau. Qua hình ảnh hai con chó, chúng ta thấy khi có món ngon, khi cần no bụng mình, tình đồng loại không còn có mặt. Chúng có thương nhau không? Nếu không thương, tại sao lại liếm nhau một cách trìu mến, vật lộn nhau một cách thân tình. Thế mà chỉ cần có một cục xương, một tô cơm, chúng liền đổi tình bạn trở thành địch thù. Tình người có thế không?

Có một gia đình ở tỉnh xa đến qui y với chúng tôi. Thời gian sau, những đứa con khôn lớn, cha mẹ già yếu. Cha mẹ tương đối khá giả, nên làm di chúc chia của cho con. Trong di chúc không biết phân chia thế nào, vài đứa con chạy lên tìm tôi nhờ khuyên giải hộ cho cha mẹ chúng phân chia công bằng, đừng cho đứa nhiều đứa ít, khiến con cái thấy cha mẹ bất công không tốt. Tôi liền khuyên chúng nó: "Cha mẹ sanh ra con, nuôi dưỡng cho học hành đến lớn khôn, lập gia đình có đôi bạn rồi, công ơn cha mẹ không thể nào kể hết. Giả sử cha mẹ nghèo không có tiền của thì con cái cũng phải làm ra tiền để nuôi dưỡng cha mẹ, mới tròn bổn phận làm con. Huống là cha mẹ khá, con đã khỏi nuôi, lại được chia của cho, dù được bao nhiêu cũng tốt, đòi hỏi thêm làm gì để phiền lòng cha mẹ. Tụi con thấy, có lắm gia đình cha mẹ chết sớm, nhà nghèo, con cái cũng phải bươn chải để sống, vậy mà cũng có nhiều người lập nên sự nghiệp. Sánh với tụi con hiện nay quá tốt, cha mẹ còn sống, lại được chia của, dù ít cũng hơn người ta quá nhiều rồi. Thôi, là con hiếu phải nghe lời cha mẹ, đừng phiền trách tổn phước." Chúng không bằng lòng, thưa với tôi thế này: "Thà là không có gì hết, còn có mà chia đứa nhiều đứa ít là bất công, không chấp nhận được." Tôi đành im lặng. Chúng chào tôi ra về với vẻ còn bực tức. Không bao lâu, cha mẹ chúng đến thăm tôi. Nhân khi thăm hỏi, tôi đem việc chia của cho con ra khuyên: "Làm cha mẹ, hai đạo hữu phải xử sự với con cái cho công bằng. Nếu có của nhiều chia cho chúng nhiều, có ít chia cho chúng ít, đừng để đứa nhiều đứa ít nó phân bì không tốt." Hai vợ chồng thưa với tôi: "Bọn con của chúng con, đứa nào phá của thì chúng con chia ít, đứa nào biết giữ của thì chia nhiều, như vậy mới công bằng." Ðến đây tôi hết ý kiến. Thời gian sau, tôi nghe những đứa con được chia của ít, đã kiện cha mẹ chúng ra tòa. Tôi đành thở dài, cảm thấy mình bất lực, không đủ biện tài để giáo hóa đệ tử, thật đáng buồn! Song càng đau buồn hơn khi thấy con người là khôn ngoan hơn con vật, vậy mà cũng vì sự ăn mặc tài sản, đối với người thân trở thành kẻ thù. Thiết nghĩ ai thân hơn anh em, ai tình thâm nghĩa nặng bằng cha mẹ, mà chỉ vì một chút ít tài sản, biến thân thành thù, đổi ân nghĩa thành đối địch. Thật tình đời càng ngẫm càng đau lòng biết mấy!

Nhân loại trên hành tinh này có thật tình thương nhau không? Nếu quốc gia này với quốc gia khác giao hảo tốt đẹp với nhau, khi quốc gia này bị thiên tai bão lụt, hoặc động đất, quốc gia kia liền gởi lương thực, thuốc men, tiền bạc sang giúp đỡ. Ðến khi nào đó, hai nước va chạm quyền lợi nhau, nếu dùng tài ngoại giao bàn luận mà không giải quyết xong, sẽ dùng đến quân đội vũ khí để sát phạt nhau. Người ta thương nhau chỉ khi nào không đụng chạm đến quyền lợi, một khi đụng chạm đến quyền lợi, sẵn sàng sát phạt nhau. Bởi vậy trên thế gian này thân thù thay đổi khó lường. Tình thương của nhân loại bị giới hạn trong một phạm vi nhất định, quá phạm vi đó tình thương liền tan biến. Cho đến những người nhân danh mang tình thương đến cho nhân loại, song cũng bị hạn chế trong những điều kiện nhất định nào đó, ngoài ra nó có thể biến thành địch thù.

Qua những dữ kiện trên, khiến chúng ta nghi ngờ tình thương con người có thật hay không? Hay nó chỉ có trên ngôn từ, ngoài cửa miệng? Ðây là chỗ bi quan của những nhà đạo đức chân chánh, cũng là tiếng còi báo nguy của những người làm việc từ thiện xã hội.

Với con mắt của Phật giáo, muốn nuôi dưỡng tình thương cho được sinh sôi nẩy nở mãi và vượt ra ngoài phạm vi giới hạn, chúng ta phải dùng con mắt trí tuệ thấy rõ thân phận của con người. Sở dĩ chúng ta khép chặt cửa tình thương là bị tham lam cuồng nộ, si mê thôi thúc che đậy. Một khi con mắt trí tuệ mở sáng rồi thì ba con quỉ ác độc ấy bị yếu thế. Từ đó cánh cửa tình thương chúng ta mới mở rộng thênh thang. Làm sao chúng ta mở sáng mắt trí tuệ? Chúng ta phải nhìn xem, phải xét kỹ đời sống con người sự thật như thế nào! Mạng sống của chúng ta được bao lâu? Trong khoảng thời gian sống của chúng ta có an ổn hoàn toàn không? Những người trước chúng ta và đồng thời với chúng ta có thực sự hạnh phúc không? Chỉ cần quán sát kỹ ba vấn đề này thì con mắt trí tuệ của ta bừng sáng.

Trước nhất chúng ta quán sát mạng mình sống được bao lâu? Thật là không có gì bảo đảm và cố định hết. Chúng ta đang sống ở phút giây này là biết mình đang sống, qua phút giây khác chưa biết mình ra sao. Biết bao cái chết chóc đang chờ chực sẵn bên mình và trong người mình. Bước đi sẩy chân cũng có thể té chết. Lái xe sơ ý cũng có thể đụng chết. Ngồi phi cơ hỏng máy cũng bị rơi chết. Một mạch máu não vỡ cũng chết. Quả tim ngưng đập cũng chết v.v... Bởi thế, Phật bảo *"mạng người sống trong hơi thở"*. Ðã biết mạng sống mình là bất định, là vô thường, không có một tí gì bảo đảm, tại sao chúng ta không thương yêu nhau, đùm bọc nhau trong những giờ phút mà chúng ta còn được sống với nhau? Tham lam thù hận để làm gì, để cho ai, khi mạng sống của mình rất mỏng manh rất tạm bợ? Tại sao chúng ta không xí xóa cho nhau, không hòa thuận với nhau để cho những phút giây sống này được an lành vui vẻ. Chính nhờ thấy rõ mạng sống của mình chợt còn chợt mất mà lòng tham lam thù hận tan biến dần, lòng thương nhân loại cùng chung số phận như mình càng rộng mở.

Thứ đến, chúng ta quán sát xem từ khi mở mắt chào đời đến phút giây chúng ta hiện sống này, toàn khoảng thời gian đó đời sống của chúng ta có hoàn toàn an ổn không? Chắc chắn ai cũng trả lời rằng không. Bao nhiêu năm qua, đời sống của chúng ta đã từng trải lắm nỗi gian truân, bao lần đau khổ. Nào là thân thể bệnh hoạn, nào là gặp cảnh bất như ý, nào là làm ăn thất bại, nào là tình đời đen bạc..., ôi làm sao mà kể cho hết. Ðời sống của chúng ta đã khổ như thế, đời sống của người nào có khác gì? Tại sao chúng ta không thương yêu, không thông cảm, cùng chia sớt nỗi khổ cho nhau, lại ôm thù chuốc hận làm gì? Ðã cùng chung thân phận đau khổ như nhau, chúng ta nên khuyên lơn an ủi để làm vơi cạn đôi phần đau khổ cho nhau. Ðây là hoa tình thương đang chớm nở trong lòng chúng ta.

Cuối cùng chúng ta hãy quán sát những người trước và những người đồng thời với chúng ta có ai hoàn toàn hạnh phúc chăng? Những người trước chúng ta, có những kẻ một thời nổi tiếng hào hoa phong nhã, đến nay chỉ còn thân tàn ma dại; có những người một thuở oanh liệt hào hùng, nhưng hiện nay là kẻ phế nhân; có những người trước kia thừa tiền mứa của, nay chỉ còn là kẻ bần hàn... Ðến những người sống đồng thời với chúng ta, có những bạn thân đã từ giã chúng ta đi về thế giới bên kia; có những người đang bị bán thân nằm trên giường bệnh; có những kẻ làm ăn không đủ sống; có những người thừa của thì con cái lại mất nết hư thân... Những kẻ trước và người đương thời kể cả chúng ta có ai dám bảo rằng *"đời tôi hoàn toàn hạnh phúc"*. Cuộc đời đã không hạnh phúc thì chúng ta say mê nó để làm gì? Tại sao chúng ta không đánh thức nhau, lay tỉnh nhau, đừng để cạm bẫy của cuộc đời lừa. Hạnh phúc của cuộc đời chỉ là cái bóng mờ trước mắt, đuổi bắt chúng chỉ chuốc nhọc nhằn. Vì tranh nhau đuổi bắt hạnh phúc nên con người phải va chạm nhau, nảy sanh oán hờn, thù địch nhau, tạo thành chuỗi khổ đau vô tận. Chúng ta xét kỹ, thấy rõ rồi cố gắng đánh thức, kêu gọi nhau hãy dừng chân, đừng đuổi bắt vô ích. Ðây là tình thương chân thật phát xuất từ đáy lòng của chúng ta.

Qua ba phần quán sát trên khiến chúng ta mở sáng con mắt trí tuệ, từ đây dấy khởi tình thương chân thật. Chính tình thương này mới không bị giới hạn, không có điều kiện hạn chế, và mở rộng thênh thang. Nhờ trí tuệ sáng ngời này, ba thứ độc tham sân si mới chịu lui bước. Song muốn có trí tuệ, chúng ta phải có những giây phút an tĩnh, ngồi lại quán sát tận tường. Chúng ta đừng bị suốt ngày chôn mình trên bàn giấy, trong cơ xưởng, tối lại dán mắt trên màn ảnh Ti-vi, thì trí tuệ chúng ta không có cơ hội phát triển.

Tuy nhiên cội nguồn tình thương chưa hẳn khô cạn, vẫn còn những mạch nước ngầm trong lòng đất nhân loại mà chúng ta ít khi khơi dậy. Chính đây là những tia hy vọng của con người, của những nhà đạo đức chân chính.

Một bà Phật tử thuật chuyện cho tôi nghe: Bà là người đang sống ở đô thị, quê bà ở tỉnh Vĩnh Long cách xa tỉnh khoảng hai chục cây số. Một lần bà về quê, đến tỉnh Vĩnh Long sang xe về quê bà. Một chiếc xe cũ kỹ mà hành khách chật như nêm, xe chạy khỏi tỉnh khoảng năm cây số, có một hành khách đón xe giữa đường. Xe dừng rước khách, bà thấy một cậu thanh niên độ trên hai mươi tuổi, mặc quần cụt, áo sơ mi. Chú lơ xe thúc lên nhanh, cậu thanh niên vội vàng phóng lên xe, chân chạm phải cánh cửa xe, toác da đổ máu. Cậu ta ngồi xuống bên cạnh bà mà vết thương ở bắp chân vẫn tuôn máu. Bà trông thấy liền mở túi xách lục soát tìm được một ít bông gòn, bà xé đưa cậu ta bảo chặm máu và đè cứng chỗ vết thương. Bà lục trong túi được chai thuốc đỏ, mớ bông gòn còn lại bà thấm thuốc đỏ đắp lên vết thương. Thấy máu còn chảy, bà lôi chiếc khăn tay trong túi ra, xé đôi, băng nịt lại thật chặt. Kế còn thừa một ít bông gòn, bà thấm thuốc đỏ lau chung quanh vết thương cho cậu. Cậu thanh niên được bà cụ bảy muơi tuổi săn sóc vết thương một cách nhiệt tình chân thiết, khiến đôi mắt cậu nhìn bà với vẻ ngạc nhiên kính quí. Mọi người trên xe đều hướng mắt nhìn bà với cái nhìn mến phục. Ðến điểm xuống xe, cậu thanh niên bước xuống trước, vết thương ở chân đã khô máu, bà cụ xuống sau. Cậu chờ bà cụ xuống xong, cúi đầu chào bà rồi mới ra đi, đi một đoạn cậu còn nhìn xem bà lão đi về lối nào!

Cũng bà Phật tử trên, bà dẫn một đứa cháu ngoại trai độ mười ba tuổi lên Tu viện Chân Không thăm chúng tôi. Gặp lúc chư Tăng xẻ mít chín, nhằm loại mít ngon nhất vườn chùa để dùng trong nửa giờ nghỉ công tác, thầy Tri khách chia hai bà cháu một phần khiêm nhường dùng lấy thảo. Hai bà cháu dùng độ muời múi mít, còn lại một phần ba, bà bảo cháu: *"Bà cháu mình nhường một phần ba này để cho người ăn xin"*. Thằng bé đang ăn ngon miệng đành phải dừng tay. Bà đi tìm một bao nylon rửa sạch, lột từng múi mít bỏ vào bao nylon, xong xuôi bà cột lại để vào túi xách. Vài giờ sau, hai bà cháu từ giã chúng tôi xuống chợ về thành phố. Xuống chợ, bà đi tìm những người ăn xin tặng mít cho họ xong, bà mới lên xe về. Mấy múi mít thật không có giá trị bao nhiêu, nhưng khi mình đang ăn ngon miệng mà nhớ đến những người ăn xin ở đầu đường xó chợ không được nếm món ăn này, bà liền dừng tay, ngăn cháu để nhường phần cho những người xấu số ấy. Thật là một tấm lòng vàng ngọc, một tình thương tràn trề ở thế gian này ít thấy. Thử nghĩ nếu tất cả chúng ta đều có một tình thương vô hạn như bà thì xã hội đang nghèo khó của chúng ta sẽ giảm khổ đau biết mấy. Còn nhiều người có tấm lòng vàng như bà, hoặc trội hơn, mà chúng tôi chưa biết, có khi đã biết mà lại quên. Mong rằng nhân loại sẽ được nhiều người luôn nhớ đến những kẻ khổ đau, để chia cơm xẻ áo với họ, khiến hành tinh chúng ta sẽ trở thành cõi Cực lạc ở mai sau.

Tình thương vô điều kiện không giới hạn, nhà Phật gọi là tâm từ bi. Tâm từ bi này nhờ động cơ trí tuệ thúc đẩy mới đủ sức đập tan những cánh cửa bản ngã, gia đình, phe nhóm, tôn giáo, quốc gia... mở rộng thênh thang không giới hạn. Người sẵn tâm từ bi thì, khi mình được ăn ngon nhớ đến kẻ đói khát, mình thành công thương người thất bại, mình vui sướng nhớ đến kẻ khổ đau, mình giàu sang nghĩ đến kẻ nghèo khó, mình hơn thương kẻ thua..., do đó mà dứt được tâm ích kỷ ngạo mạn. Nhân loại đang đau khổ lắm rồi, chúng ta không thể dang tay cứu vớt hết được, ít ra chúng ta cũng đừng chồng chất khổ đau thêm, khiến quá sức chịu đựng của con người. Chúng ta hãy kêu gọi nhau thức tỉnh cơn ngủ si mê, đừng chạy theo tham lam cuồng nộ, dừng tay gieo rắc đau khổ lên nhau. Hạnh phúc không bao giờ có nơi con người ích kỷ tham lam. Hạnh phúc không bao giờ có ở con người si mê cuồng nộ. Hạnh phúc chỉ có với người luôn chan rải tình thương.
