# Cuộc đời tương đối mà! {- #cuoc-doi-tuong-doi-ma}

Hầu hết chúng ta đều mắc phải cái bệnh *"đòi hỏi tuyệt đối"*. Giàu thì muốn mình giàu hơn tất cả, sang cũng muốn mình sang hơn tất cả, cho đến đẹp, giỏi, khen, đều là hơn tất cả. Có cái gì thua kém hơn người là buồn, tủi, bực dọc, không hài lòng. Do đó cuộc sống ít khi có hạnh phúc, vì thấy mình còn thua người này kẻ nọ. Hoặc than trách người thân của mình sao không được như ý mình muốn. Những nỗi khổ đau buồn bực ấy đều do không hiểu *"cuộc đời tương đối mà!"*.

## Muôn vật tương đối {- #muon-vat-tuong-doi}

Muôn vật hiện có trên cõi đời đều là tương đối. Người thì có nam nữ, loài vật thì có giống cái giống đực, điện thì có điện âm điện dương..., từ lý tương đối ấy mà sanh ra vạn vật. Chính lý tương đối là gốc sinh hóa vô cùng vô tận. Nếu chúng ta tách rời sự vật ra từng phần đơn độc thì sự sinh hóa phải dừng lại. Cuộc sống chúng ta là tương quan trong cái đối nghịch, sinh trưởng trong cái chống chọi. Như thế, chúng ta làm sao tìm ra sự bình an hoàn toàn, sự hạnh phúc miên viễn trong cuộc đời tương đối. Sáng suốt nhất là, chúng ta nhìn sự tương đối là lý đương nhiên, không oán hờn, không trách cứ trước mọi sự việc trái ngược nhau. Ðồng thời chúng ta khéo lợi dụng lý tương đối tạo thành những công năng hữu ích cho con người. Thí dụ nước với lửa là đối nghịch nhau, song chúng ta khéo dùng lửa đun sôi nước để nấu chín các thức ăn... Ðiện âm điện dương đối nghịch nhau, chạm nhau là tóe sáng, con người khéo lợi dụng sự phát sáng đó tạo ra vô số công năng của điện... Chừng đó chúng ta mới thấy sự hữu dụng của nước và lửa, của điện âm và điện dương phục vụ cho con người một cách hữu hiệu. Chúng ta cứ sợ nước dập tắt lửa, tách rời xa chúng thì chúng ta có được lợi gì trong cuộc sống. Như vậy, chúng ta không sợ sự đối nghịch của vạn vật, mà chỉ khéo léo sử dụng sự đối nghịch một cách hữu hiệu trong cuộc sống của chúng ta.

## Bản thân con người tương đối {- #con-nguoi-tuong-doi}

Con người có hai phần vật chất và tinh thần, cả hai phần này đều là tương đối.

### Phần vật chất {- #phan-vat-chat}

Ðức Phật phân tích một cách đơn giản, trong cơ thể con người do bốn thứ cấu tạo thành. Phần cứng rắn là đất, phần thấm ướt là nước, phần nóng ấm là lửa, phần chuyển động là gió. Bốn phần này chung họp làm thân con người và tồn tại một thời gian. Nếu thiếu một trong bốn phần, thân này phải bại hoại. Bản thân bốn phần này lại đối nghịch nhau, nước chống với lửa, gió chọi với đất. Cho nên trong thân khi nước thịnh lửa suy thì sanh ra bệnh lạnh, hoặc phù thũng..., ngược lại khi lửa thịnh nước suy thì sanh ra bệnh nóng, nhức đầu..., khi gió thịnh đất suy thì sanh ra bệnh đau nhức khắp thân thể; khi đất thịnh gió suy thì sanh ra bệnh tê liệt, khó thở... Do đó mang thân này suốt đời chúng ta phải lo điều hòa tứ đại. Tứ đại được điều hòa thì thân mới khỏe mạnh an ổn, ngược lại thì đau yếu liên miên. Bốn thứ đối nghịch này, chúng ta có nên hủy hoại nó không, nếu chúng ta còn muốn sống? Hay mỗi ngày chúng ta cố gắng điều hòa chúng để cho thân này được an ổn. Bốn thứ thù địch nhau, song nhờ bốn thứ mà thân này mới tồn tại. Như thế, chúng ta sợ ghét sự chống đối hay khéo điều hòa sự chống đối? Muốn thân này được sống còn an ổn, không cách nào hơn chúng ta phải biết điều hòa chúng một cách thích hợp. Ðó là khôn ngoan, là biết sống.

### Phần tinh thần {- #phan-tinh-than}

Nội tâm chúng ta đối nghịch nhau rất là phức tạp. Ở đây tạm chia tâm niệm thiện và tâm niệm ác đối nghịch nhau. Song khi niệm ác dấy lên thì niệm thiện ẩn đi, ngược lại khi niệm thiện dấy lên thì niệm ác trốn mất, hai thứ đối nghịch mà không đồng thời. Vì thế nếu biết tu, chúng ta luôn luôn nuôi dưỡng niệm thiện thì niệm ác lặn mất. Nếu người không biết tu, cả ngày dung chứa niệm ác thì niệm thiện không bao giờ xuất hiện. Nuôi dưỡng niệm thiện là bậc hiền thánh, dung chứa niệm ác là kẻ bạo tàn. Chúng ta trọn quyền tạo lập cho mình một chỗ đứng vào hàng thánh thiện, cũng chính chúng ta tự bước lùi vào hang quỉ, chỗ thú cầm. Không ai bắt buộc, không ai lôi kéo chúng ta đến nơi này hay nơi nọ. Do đó, đức Phật dạy chúng ta tu quán Từ bi để trừ tâm sân hận, quán Tứ niệm xứ để diệt mê lầm, hoặc niệm danh hiệu Phật để át tạp niệm... Chúng ta có đủ khả năng làm hiền thánh, chúng ta cũng có đủ chủng tử ngạ quỉ, súc sanh. Bởi vậy nói tu tâm là chúng ta khéo điều phục những tâm niệm xấu ác, nuôi dưỡng những tâm niệm hiền thiện. Khi sắp lâm chung, những tâm niệm nào mạnh sẽ lôi chúng ta đến cảnh tương xứng. Vì tâm niệm là gốc của luân hồi sanh tử.

Thế thì bản thân chúng ta từ vật chất đến tinh thần đều là tương đối. Như vậy, chúng ta không ưa tương đối, chạy trốn tương đối có được không? Quả là điều dại khờ. Chúng ta phải khôn ngoan sáng suốt tìm mọi cách điều hòa cho thân an ổn, chinh phục cho tâm hiền thiện. Ðây là việc làm của người biết sống và sống vươn lên.

## Tương quan mình và người {- #tuong-quan-minh-va-nguoi}

Trong cuộc sống tương quan giữa mình và mọi người chung quanh, hầu hết chúng ta mắc phải cái bệnh *"cầu toàn trách bị"*. Chúng ta đòi hỏi những người sống gần với mình phải vẹn toàn một trăm phần trăm *(100%)* như ý mình muốn, phải đầy đủ hoàn toàn những điều như tâm mình tưởng. Nếu những người thân chỉ được tám chục phần trăm *(80%)* trong sự đòi hỏi của mình, sống gần gũi lâu ngày còn hai chục phần trăm bất như ý này sẽ làm cho chúng ta sinh bực bội chán chường. Sao chúng ta không đặt lại câu hỏi, chính mình có được vẹn toàn mọi điều như ý mình muốn chăng? Hẳn là không. Mình đã không được vẹn toàn, sao lại đòi hỏi người phải vẹn toàn, có phải là bất công, phi lý không? Ngày xưa ở các nước Ðông phương quyền lập gia đình cho con cái là ở cha mẹ, cha mẹ định sao con cái phải nghe vậy. Do đó có những gia đình vợ chồng không hòa thuận vì không cảm thông nhau, nên đi đến đổ vỡ ly dị. Ngày nay ở các nước Tây phương con cái được quyền chọn lựa đôi bạn cho mình. Họ còn có quyền sống gần với người họ chọn lựa một thời gian, sau mới quyết định thành đôi bạn hay không, cha mẹ không được can thiệp đến đời tư của họ. Thế mà khi đã thành đôi bạn, lại vẫn ly dị nhau. Ðây là lỗi tại ai, cha mẹ ép buộc chăng? Quả thực đây là cái bệnh đòi hỏi vẹn toàn một trăm phần trăm *(100%)* theo ý mình muốn. Bởi không có ai thỏa mãn sự đòi hỏi của mình nên từ thân biến thành sơ. Thế là cứ ly dị mãi, đến già trở thành người cô độc. Chúng ta còn thêm lắm bệnh. Nào là muốn ai cũng khen mình, có người chê là buồn khổ. Muốn mọi người gần mình phải tuyệt đối tuân theo sự sắp đặt của mình, nếu 80 điều họ theo, còn 20 điều họ chống là giận dữ bực tức. Ðòi hỏi người thân của mình phải tốt tuyệt đối, nếu họ có vài ba điều xấu liền chán nản muốn lánh xa. Ðến tình cảm thương yêu cũng vậy, bắt buộc người thân của mình phải thương yêu mình tuyệt đối, nếu bị chia xẻ cho ai, dù người ấy là thân thuộc hợp lý, vẫn cảm thấy buồn. Chính vì lòng tham lam đòi hỏi quá đáng, khiến người chung quanh chúng ta từ từ muốn xa lánh chúng ta. Ðây là vì không biết cuộc đời là tương đối, nên không thông cảm với mọi người chung quanh, kết quả tự chuốc lấy khổ đau cô độc. Trái lại, chúng ta tập nhìn mọi người với cặp mắt tương đối, không đòi hỏi quá đáng, dễ cảm thông tha thứ nhau. Ðược vậy đời sống sẽ vui tươi, người thân đông đảo, dễ dàng đạt được hạnh phúc.


## Bệnh thần tượng {- #benh-than-tuong}

Chúng ta dễ mắc cái bệnh *"thần tượng hóa"* người mình quí kính. Người mình quí kính là thánh thiện một trăm phần trăm *(100%)*, nếu thân cận thời gian, thấy vị ấy có một vài điều còn phàm tục, *"thần tượng"* liền sụp đổ. Từ đây ta sanh tâm khinh lờn cho đến bất mãn, không còn tin tưởng vào ai nữa. Ðây là một trọng bệnh, khiến ta tự cao ngạo mạn, mất hết lòng tin. Khi trước do tin vào bậc thầy thánh thiện nên ta tinh tấn tu hành, nay mất lòng tin rồi nên sanh bê tha hư đốn. Tại sao ta không xét nét kỹ càng xem, bậc thầy kia hơn mình bao nhiêu phần? Nếu ta có hai mươi phần trăm *(20%)* tốt, vị thầy có đến bốn chục phần trăm *(40%)* hay sáu chục phần trăm *(60%)* thì rất đáng cho mình học tập theo. Vì vị ấy đã tốt hơn mình gấp đôi gấp ba, còn chê trách nỗi gì. Bởi vì vị thầy chưa phải là thánh, là Phật làm sao hoàn toàn thánh thiện được. Chúng ta cảm thông vị ấy đang tu, là còn những cái dở để sửa, để bỏ. Bồ-tát vẫn còn vi tế vô minh, nếu sạch hết vô minh là thành Phật. Biết rõ cái tốt của những vị mình quí kính là tương đối thì mình kính tin vừa phải, chừng mực, không *"thần tượng hóa"*. Nếu thấy vị ấy còn vài nét phàm tục, mình cũng cảm thông tha thứ, vì đây là người đang tu đang tiến, đừng đòi hỏi quá đáng. Hoặc giả ngày xưa mình tin vào vị thầy gần như tuyệt đối, vị ấy dạy gì mình cũng cố gắng làm cho được, nhờ đó trên đường tu mình tiến bộ vượt bậc. Nay mình mất lòng tin ở vị thầy ấy, sinh tâm lui sụt, đây là điều sai lầm. Tại sao mình không nghĩ, ta tu là ta tiến, thầy tu thì thầy tiến. Ðâu phải thầy tu hay ta mới tiến, thầy tu dở ta bị lùi. Phải tin vào mình, phải trông cậy vào mình. Phật dạy: *"các ông phải tự thắp đuốc lên mà đi"*, lại "*các ông phải tự làm cồn đảo cho mình"*. Thế nên, không vì *"thần tượng sụp đổ"* mà ta lùi bước. Chính chúng ta phải nhìn các bậc thầy quí kính vẫn là tương đối, thì chúng ta khỏi chới với khi trông thấy vài nét phàm tục của các Ngài.

## Lục tổ dạy ba mươi sáu pháp đối {- #ba-muoi-sau-phap-doi}

Trong kinh Pháp Bảo Ðàn, Lục tổ dạy đệ tử sau này có ai hỏi đạo nên dùng 36 pháp đối để trả lời thì không sai tông chỉ nhà Thiền. Nếu người hỏi *"có"* lấy *"không"* đáp, người hỏi *"sáng"* lấy *"tối"* đáp... Tại sao? Vì nhân nơi *"không"* mà lập *"có"*. Bởi có cái *"không"* mới thành lập cái *"có"*, không có cái *"không"* thì cái *"có"* cũng chẳng thành. Ngược lại, nhân cái *"có"* mà lập cái *"không"*, nếu chẳng có cái *"có"* thì cái *"không"* cũng vô nghĩa. Ðến cái sáng cái tối cũng thế. Do tối mới lập sáng, nhân sáng mất nói là tối. Hai cái nương nhau mà thành, không có thật pháp. Tất cả sự vật ở thế gian đều là đối đãi nhau mà lập, không có một pháp nào thật. Thế mà chúng ta chấp thật pháp, thật ngã, tăng trưởng si mê, chìm đắm mãi trong biển luân hồi sanh tử. Dưới con mắt của Phật, của Tổ thấy rõ các pháp như huyễn như hóa, nên các ngài ung dung tự tại vượt ra ngoài vòng sanh tử luân hồi. Thấy tất cả là tương đối hư giả là cái thấy của người giác ngộ.

## Chỉ tâm chẳng sanh chẳng diệt là tuyệt đối {- #tuyet-doi}

Tuy nhiên trong cuộc đời tương đối vẫn có cái tuyệt đối mà ít ai biết đến. Chúng ta cứ quen chạy theo hình sắc thanh âm là những thứ vô thường sanh diệt. Ngay cái sanh diệt lại đòi cho được tuyệt đối, quả là chúng ta bắt bóng mò trăng. Làm gì có, ngay cái đối đãi sanh diệt lại là tuyệt đối vô sanh. Khi chúng ta vin theo hình thức sự vật mà mong được cái chân thật chẳng sanh chẳng diệt. Hãy nghe hai câu sau trong bài kệ trình kiến giải lên Ngũ  tổ của người cư sĩ họ Lư: *"Xưa nay không một vật, chỗ nào dính bụi nhơ"* (Bản lai vô nhất vật, hà xứ nhạ trần ai). Có vật là vô thường sanh diệt, dù cứng như chất kim cương cũng là vô thường sanh diệt. Chỉ có tâm thể không hình tướng, không dấy động mới là bất sanh bất diệt. Tâm thể vượt ngoài đối đãi hai bên, vĩnh hằng bất biến. Vừa thấy hai bên là mất tâm thể rồi. Cho nên Tổ Tăng Xán kết thúc bài Tín Tâm Minh *(Ghi Tin Tâm)* nói: "Tín tâm bất nhị, bất nhị tín tâm" *(Tin tâm không hai, không hai tin tâm)*. Có hai là còn đối đãi, không hai thì đối đãi với cái gì. Chính cái vượt ngoài đối đãi mới thật là tuyệt đối. Cái tuyệt đối có sẵn nơi mọi con người chúng ta, không phải tìm kiếm bên ngoài. Biết buông tâm niệm đối đãi, sống bằng thể không đối đãi là người giác. Trái lại, chạy theo tâm niệm đối đãi sanh diệt, quên mất tâm thể bất sanh bất diệt là người mê.

## Kết thúc {- #ket-thuc}

Con người chán nản ê chề khổ đau cùng cực, vì những thần tượng của mình dựng lên đều sụp đổ. Còn tin tưởng vào đâu khi lòng tin tuyệt đối dồn vào các thần tượng, mà nay tan vỡ hết rồi. Ðây là người mắc bệnh thiếu thực tế, lúc nào cũng lý tưởng hóa kẻ khác. Khi lý tưởng bị thất vọng, họ đâm ra thù ghét chán chường. Cộng thêm bệnh đòi hỏi quá đáng, khiến họ không bằng lòng một người nào trên thế gian này. Thế là, họ đang sống trong đông đảo quần chúng, mà cảm thấy như mình lang thang trong bãi sa mạc. Sự chán đời tuyệt vọng của những người này phát xuất từ sự gởi gấm tất cả lòng tin vào kẻ khác. Chúng ta phải khôn ngoan nhìn mọi người bằng con mắt tương đối, tin mọi người bằng lòng tin giới hạn. Chúng ta sẽ bằng lòng trong cuộc sống này, và sẽ cảm thông tha thứ những người thân với mình khi họ phạm phải sai lầm. Chúng ta còn chỗ nương tựa duy nhất là chính mình. Mình sẵn có hòn ngọc quí mà lâu nay đã quên lãng. Hôm nay khéo tay mở chéo áo lấy hòn ngọc đem ra dùng, đời ta sẽ hạnh phúc biết là bao!
