# Đức Phật là bậc thầy các nhà khoa học {- #duc-phat-la-nha-khoa-hoc}

Phật *(Buddha)* là một từ ngữ để chỉ người giác ngộ viên mãn. Ðức Thích-ca Mâu- ni *(Sàkyàmuni)* là người đã giác ngộ, nên chúng ta gọi Ngài là Phật. Giác ngộ là thấy biết mọi chân lý về vũ trụ và nhân sinh. Từ chỗ giác ngộ này, đức Phật chỉ dạy các môn đồ còn ghi chép lại thành Tạng kinh. Trong Tạng kinh chứa đựng đầy dẫy những chân lý, dù trải qua hơn hai mươi lăm thế kỷ vẫn còn giá trị nguyên vẹn, không do thời gian làm suy giảm. Ngày nay chúng ta nghiên cứu Tạng kinh thật chín chắn, càng phát hiện những chân lý ấy gần gũi và thích hợp với khoa học một cách không ngờ. Trong bài viết này, chúng tôi chỉ giới thiệu tổng quát vài nét cương yếu để độc giả suy ngẫm.

## Về vũ trụ {- #ve-vu-tru}

Ðức Phật ra đời trên sáu thế kỷ trước Công nguyên, còn các nhà khoa học được biết đến, mới có từ thế kỷ thứ mười tám sau Công nguyên. Thế mà ở thời gian ấy đức Phật nhìn trong vũ trụ thấy thế giới nhiều không thể kể hết, nên trong kinh thuộc Hán tạng có những câu *"Hằng hà sa số thế giới"*, nghĩa là thế giới nhiều như cát sông Hằng *(Ganges)*, hoặc câu *"vi trần sát"* nghĩa là cõi nước *(sát)* nhiều như những hạt vi trần. Ðến nay các nhà thiên văn học nhờ kính viễn vọng nhìn thấy trong bầu hư không có không biết cơ man là thế giới. Vô số ngôi sao lấp lánh hiện trên nền trời trong lúc ban đêm, mà mắt chúng ta nhìn thấy được, là những hành tinh *(thế giới)*, còn không biết bao nhiêu hành tinh khác quá xa, mắt chúng ta không thể nhìn thấy được. Chính đây là bằng chứng cụ thể, nhờ khoa học giúp chúng ta hiểu được lời Phật dạy cách đây trên hai mươi lăm thế kỷ. Lại nữa, có lần đức Phật cùng các thầy Tỳ-kheo đi vào rừng, nhìn thấy những lá cây rơi lả tả, những lá vàng úa sắp lìa cành, đồng thời có những chồi non vừa nẩy lộc và những mầm vừa nhú khỏi vỏ cây, Ngài dạy các thầy Tỳ-kheo: *"Thế giới đang hoại, sắp hoại và đang thành, sắp thành, cũng như lá cây trong rừng đang rụng, sắp rụng và đang nẩy chồi, sắp nẩy chồi"*. Vì thế, đức Phật thường dạy thế giới có bốn thời kỳ *"thành, trụ, hoại, không"*. Ngày nay các nhà khoa học cũng thừa nhận thế giới phải trải qua bốn thời kỳ như thế. Ðây là cái nhìn thích hợp giữa Phật học và khoa học mà cách nhau thời gian quá xa.

## Về vạn vật {- #ve-van-vat}

Vạn vật sanh thành và hoại diệt trên đời, dưới con mắt trí tuệ của đức Phật đều do *"duyên khởi"*. Duyên khởi là nhân duyên sanh khởi, không có một sự vật nào hình thành mà không do các duyên nhóm họp. Nếu nói sự vật ngẫu nhiên tự thành, hoặc có bàn tay mầu nhiệm nào tạo dựng đều không đúng sự thật. Ðức Phật xác nhận vạn vật do nhân duyên tụ họp thì thành, nhân duyên ly tán thì hoại. Sự thành hoại của vạn vật đều do duyên, là chỗ thấy như thật của đức Phật. Bởi thế, trong kinh Phật thường dạy: *"các pháp do duyên khởi không có thực thể, các pháp do duyên khởi không có cố định"*. Không có thực thể là thuyết *"vô ngã"*, không có cố định là thuyết *"vô thường"*, mà trong kinh thường nói: *"chư hạnh vô thường, chư pháp vô ngã"*. Không khi nào có một nhân đơn thuần thành hình một vật, cũng không bao giờ có sự bất ngờ sanh ra một vật, mà phải đủ nhân đủ duyên mới thành. Vì vậy, đức Phật không chấp nhận thuyết *"nhất nhân"* và thuyết *"vô nhân"*. Với sự thật này, ngày nay khoa học đã làm sáng tỏ, chúng ta không còn gì phải nghi ngại. Hơn nữa, trước mắt chúng ta thấy vô vàn sự vật, nếu đem ra phân tích đều do nhân duyên hợp thành, không có vật nào tự thành hay do một cái gì đó làm thành. Sự thật hiển nhiên này càng làm sáng tỏ lời đức Phật dạy. Chúng ta thấy rõ Phật học và khoa học tuy thời gian cách xa mà không có giới tuyến ngăn cách.

## Về con người {- #ve-con-nguoi}

Khi Phật còn tại thế, Ngài nhìn trong bát nước thấy vô số vi trùng, trong kinh Hán tạng có câu: *"Phật quán nhất bát thủy, bát vạn tứ thiên trùng..."*. Nghĩa là: Phật nhìn trong bát nước thấy tám muôn bốn ngàn *(84.000)* vi trùng. Ngày nay nhờ kính hiển vi, các nhà khoa học thấy trong nước có nhiều vi trùng. Lại nữa, Phật nhìn trong thân người thấy có vô số vi trùng, trong kinh Hán tạng có câu *"nhân thân chi nội hữu vô số vi trùng tại trung nhi trú"*. Nghĩa là trong thân người có vô số vi trùng đang trú ẩn bên trong. Ðiều này ngày nay chúng ta chỉ cần có chút ít kiến thức khoa học là không còn nghi ngờ gì nữa.

## Nghiệp lực {- #nghiep-luc}

Nếu không có một đấng nào an bài, muôn vật làm sao được sanh thành, hoại diệt và sinh hoạt trong một trật tự nhất định? Nhà Phật nói: *"do sức nghiệp thúc đẩy và thu hút mọi vật hình thành, khi mãn nghiệp thì hoại diệt. Cũng do động lực của nghiệp nên mọi vật sinh hoạt trong một trật tự nhất định"*. Nghiệp là động lực lôi cuốn các duyên tụ họp lại thành hình sự vật; khi sức nghiệp mãn các duyên ly tán thì sự vật hoại diệt. Nghiệp có khả năng cuốn hút sự vật quay cuồng trong quĩ  đạo nhất định. Ngày nay các nhà khoa học đã nói rõ sức quay và sức hút của mọi vật trong vũ trụ. Các hành tinh trong bầu vũ trụ hoặc lớn hoặc nhỏ đều quay cuồng trong hư không và trong một quĩ đạo nhất định. Cho đến nhỏ như một hạt nguyên tử cũng quay cuồng và xoắn chặt vào nhau mà thành hình muôn vật. Ðộng lực quay và hút này là do nghiệp lực tạo nên. Nghiệp là động lực lôi cuốn theo thói quen, đồng thời cảm ứng với vật khác đồng tính nên bị thu hút. Do nghiệp chi phối nên con người và muôn vật trên thế gian được thành hình và sinh hoạt trong một phạm vi nhất định nào đó, khi sức nghiệp mãn con người và muôn vật theo đó hoại diệt. Song nghiệp có thể chuyển đổi được, không phải cứng nhắc cố định, vì nó là động lực.

Tuy nhiên thuyết nghiệp báo luân hồi đã có trước thời đức Phật, xuất phát từ các kinh Phệ-đà *(Véda)*; song với tinh thần tôn trọng chân lý, đức Phật xét thấy đúng sự thật liền ứng dụng đem dạy đệ tử tu hành. Trong đó, đức Phật có sửa đổi những phần lệch lạc theo quan niệm Bà- la-môn giáo, để lý thuyết này được hoàn chỉnh hơn. Vì vậy, ngày nay mọi người đều thừa nhận thuyết nghiệp báo luân hồi là của đạo Phật.

## Đạo Phật đặt trọng tâm ở con người {- #trong-tam-o-con-nguoi}

Chỗ thấy biết của đức Phật đúng sự thật, hợp chân lý, nên trải qua thời gian dài mà vẫn không sai chạy hay lạc hậu. Ðức Phật không dùng cái thấy biết tuyệt vời ấy để phân tích ngoại cảnh, sử dụng ngoại cảnh phục vụ con người. Ngài chỉ dùng cái thấy ấy biết ấy để soi sáng thẳng vào con người, để thấy biết tường tận về con người từ thể xác lẫn tinh thần. Biết rõ con người rồi, đức Phật dạy cách sống đúng tư cách con người, đồng thời chuyển hóa thân tâm để được an lạc trong hiện tại và mãi sau kia. Có lần đức Phật cùng các thầy Tỳ-kheo đi vào rừng Simma, Ngài dùng tay nắm một nắm lá cây đưa lên hỏi các thầy Tỳ-kheo: *"Lá cây trong tay ta nhiều hay lá cây trong rừng nhiều?"* .Các thầy Tỳ-kheo thưa: *"Lá cây trong tay Thế Tôn rất ít, so với lá cây trong rừng"*. Ðức Phật dạy: *"Cũng thế, chỗ ta thấy biết nhiều như lá cây trong rừng, những điều ta dạy các ông ít như lá cây trong nắm tay ta"*. Ðiều này khiến chúng ta thấy rõ, dù việc ấy đúng sự thật mà không cần thiết cho sự đào tạo xây dựng con người được an vui hạnh phúc hiện tại và mai sau, Phật vẫn không đem ra chỉ dạy. Phật chỉ dạy những điều cấp thiết để giải quyết mọi khổ đau cho kiếp sống con người. Vì tuổi thọ con người quá ngắn *(60-70 năm)* không đủ thời giờ để học hiểu hết mọi điều trên thế gian này.

Phần hệ trọng nhất nơi con người là tinh thần. Tinh thần sai sử thể xác tạo thành nghiệp lành nghiệp dữ, cảm thọ quả khổ, vui ở hiện tại và vị lai. Cho nên bao nhiêu lời khuyên răn của Phật đều đặt nặng sự chuyển hóa nội tâm của con người. Con người nội tâm được trong sáng thì đời sống hiện tại đầy đủ ý nghĩa, sau khi kết thúc cuộc đời mọi sự sáng trong tươi đẹp đang sẵn sàng chờ chực. Ðây là trọng tâm cứu khổ chúng sanh của đức Phật Thích-ca, cũng là của đạo Phật.

## Đạo Phật chủ trương giác ngộ, giải thoát, từ bi, bình đẳng {- #giac-ngo-giai-thoat-tu-bi-binh-dang}

Ðức Phật do giác ngộ nên thành Phật, suốt đời giáo hóa của Ngài cũng lấy giác ngộ làm trọng tâm. Người tu Phật mà thiếu giác ngộ là không phải người đệ tử chân thật của đạo Phật. Khổ đau gốc từ vô minh, muốn hết khổ đau phải dứt sạch vô minh. Chỉ có ánh sáng giác ngộ mới dẹp tan được màn vô minh, ngoài giác ngộ ra không còn cách nào dẹp được vô minh. Như chỉ có ánh sáng mới dẹp được bóng tối, ngoài ánh sáng không có cái gì dẹp được bóng tối. Vô minh không tan thì đau khổ làm sao hết được. Vì thế, phương pháp duy nhất để cứu khổ chúng sanh là giác ngộ. Ðây là nguyên nhân đạo Phật lấy giác ngộ làm chủ yếu.

Nhờ giác ngộ con người mới giản trạch được điều chân lẽ ngụy, thấy rõ cái gì trói buộc, cái gì tự do, nên chọn được lối sống thích ứng lẽ thật, phù hợp với tinh thần tự do. Tự do ở đây không có nghĩa đòi hỏi bên ngoài, nơi kẻ khác, mà tự chiến thắng những khát vọng đê hèn của mình, hàng phục được vọng tưởng điên đảo của nội tâm. Ðúng với câu đức Phật dạy: *"Thắng một vạn quân không bằng thắng mình, thắng mình mới là chiến công oanh liệt"*. Tinh thần tự do của đạo Phật là làm chủ toàn vẹn thể xác lẫn tinh thần của chính mình. Ðó là tự do tuyệt đối, cũng là giải thoát của Phật dạy.

Ðem vui và giải khổ cho chúng sanh là lòng từ bi của đạo Phật. Muốn cho mọi người hết khổ được vui, tu sĩ Phật giáo lúc nào cũng đưa cao ngọn đuốc chánh pháp cho mọi người mồi, để cùng thắp sáng trong ngôi nhà tăm tối muôn đời của mình. Bản thân mình người tu sĩ phải chiến thắng phiền não để làm mẫu mực và chỉ dạy người dẹp trừ phiền não. Vô số khổ đau của chúng sanh đều phát xuất từ si mê và phiền não. Thiếu thốn vật chất là đau khổ đã đành, có khi thừa mứa vật chất người ta vẫn đau khổ như thường. Cho nên trí tuệ là hòn ngọc quí để đổi lấy của cải và sự nghiệp, trí tuệ là ngọn đuốc soi sáng cho chúng ta tránh khỏi lạc lối lầm đường. Dứt một phần phiền não, chúng ta được một phần an lạc, hoàn toàn sạch phiền não thì còn gì làm phiền lụy chúng ta. Sau khi mở sáng con mắt trí tuệ và dứt sạch phiền não, con người mới được an vui tự tại đầy đủ. Người tu sĩ Phật giáo tha thiết cứu khổ chúng sanh bằng cách tận lực chỉ dạy cho mọi người thực hiện được trí tuệ và tự do.

Phật giáo nhìn chúng sanh đều bình đẳng trong bản tánh, chỉ có sai khác trên nghiệp tướng. Nghiệp tướng là cái sanh diệt biến động, bản tánh chưa bao giờ sanh diệt đổi thay. Cái sanh diệt biến động là tạm bợ, đã tạm bợ dù sai khác thế mấy cũng không quan trọng. Chính cái tối quan trọng là bản tánh thường hằng của chúng sanh. Cho nên đức Phật thường dạy: *"tất cả chúng sanh đều có tánh Phật"*, đó là lối nhìn bình đẳng của Phật giáo. Thấy thấu được lẽ này, chúng ta sẽ dứt được tâm tự cao ngã mạn và không còn dám khinh thường một ai. Ðây là nền tảng đạo đức chân thật, nên Bồ-tát Thường Bất Khinh thấy ai cũng nói: *"Tôi không dám khinh các Ngài, các Ngài sẽ thành Phật"*. Ðã sẵn có tánh Phật thì người nào mà tu chẳng được, chỉ do chưa thức tỉnh và lười nhác mà thôi. Do cái nhìn thấu suốt này, người tu theo đạo Phật không bao giờ có tâm kỳ thị với bất cứ nhóm nào, cũng không có tâm khinh khi miệt thị ai.

Ðạo Phật lấy giác ngộ làm gốc rễ, lấy giải thoát làm hoa trái, lấy từ bi và bình đẳng làm nhựa sống. Bốn yếu tố này rất thiết thân với nhân loại văn minh. Bất cứ nền văn minh chân chánh nào đòi hỏi con người phải có đủ trí tuệ sáng suốt, thong thả tự do, tình thương làm vơi cạn đau khổ cho con người, bình đẳng không chấp nhận giai cấp, không kỳ thị tôn giáo, chủng tộc, màu da. Nếu thiếu một trong bốn yếu tố này, dù nói văn minh vẫn chưa thực sự văn minh. Ðứng từ góc độ này mà nhìn, chúng ta thấy đức Phật quả thực đã đi trước các nhà khoa học khá xa; tương lai dù nhân loại văn minh tiến bộ đến đâu cũng khó qua mặt được đạo Phật.
