# Phá rừng tre gai {- #pha-rung-tre-gai}

Cuối năm 1992, chúng tôi suy yếu đi Vũng Tàu dưỡng bệnh, ở nhờ nhà của một Phật tử. Chủ nhà vì chúng tôi mới xây cất xong. Nhà nằm trên mảnh đất bằng phẳng, bên cạnh sườn núi đá, dưới chân là biển cả mênh mông. Gió biển thổi vào mát rượi, mang theo mùi mằn mặn của chất muối, thật là nơi thích hợp cho người dưỡng bệnh. Rất tiếc, phía sau nhà có rừng tre gai mù mịt. Nhiều người đến thăm tôi, thấy rừng tre gai gần nhà đề nghị, nên dọn sạch cho khoảng khoát. Mấy chú và một số cư sĩ nghe đề nghị hợp lý, phát tâm *"phá rừng tre gai"*.

Công việc đầu tiên của các vị ấy, đi rèn mấy cái rựa bén, cào sắt và một số lốp xe đạp. Ðủ dụng cụ rồi, họ bắt tay vào việc. Nhưng nhìn rừng tre rậm rạp, gai giương lổm chổm, ai nấy đều ớn da gà. Can đảm xông vào chặt những màng nhện chung quanh gốc tre sập xuống, họ lấy cào sắt cào cành lá tre khô ấp vào gốc. Họ dùng lửa đốt gai góc lia chia quanh bụi tre cháy rụi, bày những thân tre trống trải rất dễ chặt. Sau cùng, họ cầm rựa tận lực chặt từng cây tre, những cây tre non chặt ngọt sớt, song gặp cây tre già là dội tay. Những cây tre sống lâu năm cứng như sắt nguội, họ phải vận dụng hết sức chặt đôi ba nhát mới đứt. Những bụi tre đan chằng chịt nhau, tuy chặt đứt gốc mà không dễ gì xô ngã. Phải gắng sức tối đa và hợp lực lại, họ lôi kéo mới ngã xuống. Mặc dù ngã xuống, song từng lớp sóng tre ngập cả khu đất. Cuối cùng họ phải dùng rựa, cào sắt, khó khăn lắm mới dọn dẹp thành từng cụm, từng khóm. Ðợi tre khô, họ châm một mũi lửa cháy sạch, chỉ còn sót lại năm ba cây thân còn tươi bị cháy nham nhở. Ðến đây đã thành một khu đất trống trải phủ trên mặt một lớp tro than. Dụng cụ quan trọng trong công cuộc phá rừng tre gai này là rựa bén, cào sắt và lửa. Song có dụng cụ tốt và đầy đủ mà thiếu quyết tâm, nỗ lực và bền chí của con người thì không thể nào làm thành công. Nhờ quyết tâm, nỗ lực, bền chí của con người mà rừng tre gai chằng chịt nguy hiểm phải tiêu tan.

Cũng thế, người Phật tử muốn dẹp sạch rừng phiền não cần phải có đầy đủ dụng cụ và từng giai đoạn tiến lên mới đạt được cứu cánh giải thoát. Dụng cụ của Phật tử là kiếm trí tuệ và lửa thiền định. Từng giai đoạn tiến lên phá dẹp tà kiến và phá sạch chấp ngã chấp pháp.

Bát-nhã là kiếm trí tuệ, như rựa bén. Muốn xông vào phá rừng phiền não, Phật tử phải nhờ Văn tự Bát-nhã làm kiếm bén. Căn cứ trên Văn tự Bát-nhã, chúng ta mới nhận ra chân lý, nhân đó dẹp sạch những kiến chấp sai lầm do phong tục tập quán còn để lại và các tà kiến tạo nên. Ví như phong tục lấy rượu dùng làm lễ nghĩa, như khay trầu rượu, hoặc nói *"vô tửu bất thành lễ"*; tập quán người chết linh hồn còn mãi ở với con cháu..., tà kiến thờ thần cây đa, thờ ông táo, bình vôi... Muôn ngàn thứ chấp sai lầm chằng chịt khó phá, giống như màng nhện tre gai, phải có cây kiếm trí tuệ chặt đứt từng đoạn rã rời. Thứ đến dùng chánh định đốt sạch, như dùng cào sắt gom cành khô lá mục vào gốc, châm một mũi lửa cháy tiêu tan.

Kế đó, chúng ta dùng Quán chiếu Bát-nhã chiếu soi năm uẩn sáu trần đều do duyên hợp không có thực thể. Chiếu soi tường tận thấu đáo, chúng ta thấy rõ thân này *(ngã)* và sự vật chung quanh *(pháp)* đều không có chủ thể. Nói là ta *(ngã)* hay vật *(pháp)* chỉ căn cứ trên giả tướng hư ảo lầm chấp, chớ không có ta thật vật thật. Nhận thấy thấu đáo như thế, mọi chấp ngã chấp pháp đều tan vỡ. Ví như sau khi đốt xong màng nhện tre gai, chúng ta dùng rựa bén chặt từng cây ngã gục.

Tuy thế chưa phải là xong, người Phật tử cần phải tu tiến lên *"Thật tướng Bát-nhã"*. Kinh nói *"Bát-nhã vô tri, vô sở bất tri"*. Nghĩa là: đến Thật tướng Bát-nhã, không còn khởi tâm phân biệt tất cả pháp, nên nói *"vô tri"*; song thể hằng trong sáng muôn vật đều hiện bày rõ ràng, nên nói *"vô sở bất tri"*. Như gương sáng trên đài, gương không phân biệt tất cả vật, mà không vật nào ở trước không hiện bóng trong gương. Vô tri là định, vô sở bất tri là tuệ, đến đây thể định tuệ viên mãn. Ðược vậy, mọi phiền não đều tan nát biến thành tro bụi. Như khi những cụm tre khô rang, chỉ cần châm một mũi lửa là cháy sạch trở thành than tro. Thiền sư Huyền Giác nói: *"Ðại trượng phu bỉnh tuệ kiếm, Bát-nhã phong hề kim cang diệm" (Chứng Ðạo Ca)*. Nghĩa là: *"Người trượng phu cầm kiếm tuệ, lửa kim cang chừ Bát- nhã bén"*.  Lửa kim cang ở đây là *"Thật tướng Bát-nhã"*. Ðược Thật tướng Bát-nhã là sạch phiền não, đến bờ thanh lương. Ngài Thái Hư nói: *"Ví như có người muốn sang sông, trước phải nhờ thuyền bè, kế phải nhờ chèo bơi, sau cùng mới đến bờ kia. Thuyền bè là Văn tự Bát-nhã, chèo bơi là Quán chiếu Bát-nhã, đến bờ kia là Thật tướng Bát-nhã"*. Phá rừng tre gai phải đi từng bước một, phá rừng phiền não, chúng ta cũng phải tiến từng giai đoạn mới thu nhặt được kết quả như nguyện.

Tuy nhiên có Văn tự Bát-nhã, Quán chiếu Bát-nhã, Thật tướng Bát-nhã đầy đủ mà chúng ta thiếu quyết tâm, tinh tấn và nhẫn nhục thì tiêu diệt phiền não cũng khó thành công.

Người tu Phật thấy thân này mỏng manh như áng mây, tạm bợ như hòn bọt, quyết tâm hy sinh thân tạm bợ *(báo thân)* đổi lấy thân kim cang bất hoại *(pháp thân)*, không có gì phải ngần ngại. Khi đã nhận thấy như thế, dù lao mình vào cảnh hiểm nguy vẫn xem như trò chơi. Do đó mới có nhà đại thí chủ cắt đầu tặng vua Kế-tân, chàng dũng sĩ chặt tay dâng tổ Ðạt-ma. Chính cái quyết tâm vong thân ấy, còn rừng phiền não nào mà phá chẳng sạch.

Kế đến phải mãi mãi tinh tấn. Tinh tấn là sức gắng gổ không ngừng. Dù biết là việc tốt đáng làm mà không nỗ lực gắng sức thì việc tốt cũng khó thành công. Tinh tấn là chất nhiên liệu của chiếc xe ô tô, nhiên liệu hết thì xe phải dừng. Người ngồi xe muốn đi đến đích phải xem chừng không để cho nhiên liệu cạn. Cũng thế, người học đạo giải thoát muốn đạt đạo quả phải nuôi dưỡng sức tinh tấn không cho thiếu vắng. Thiếu tinh tấn người tu sĩ sẽ dẫm chân tại chỗ, hoặc thối lui là khác. Có tinh tấn là có đạo quả và đạt được sở nguyện của mình.

Tinh tấn là thiết yếu, song cần phải có nhẫn nhục phụ trợ thì sự tu hành mới được thành công. Vì phiền não nhiều vô vàn không thể tính kể được, chúng ta phá lớp này, lớp khác lại hiện ra, nếu không dai sức nhẫn chịu thì dễ sanh chán nản rồi thối tâm Bồ-đề. Phiền não sâu dày như đất, bù bịt như rừng, muốn đào tận đáy, muốn chặt sạch trơn, phải dày công và trải qua nhiều tháng năm mới thấy được kết quả. Nhẫn nhục là sức chịu đựng dẻo dai, đón nhận mọi khó khăn trở ngại, với thời gian dài mấy cũng không ngán. Có đủ sức chịu đựng này, dù rừng phiền não có gai góc bao nhiêu, có dày bịt đến đâu cũng bị dẹp tan phá sạch. Người tu Phật mục đích nhắm đến xa thăm thẳm, chướng ngại và hầm hố dẫy đầy, nếu thiếu đức nhẫn nhục thì có đi mà không có đến.

Tóm lại, muốn phá rừng tre gai, chúng ta phải có đầy đủ dụng cụ, cộng thêm quyết tâm nỗ lực và bền chí của con người, rừng tre gai phải tan hoang, biến thành tro bụi. Muốn dẹp sạch trần lao phiền não, người tu phải có trí tuệ, thiền định đầy đủ. Trí tuệ, thiền định là pháp tu, cộng thêm quyết tâm, tinh tấn, nhẫn nhục của con người thì *"phiền não vô tận sẽ đoạn sạch"*. Người tu là kẻ đối đầu với ma vương, là chiến sĩ tảo thanh bọn giặc phiền não. Cho nên, kiếm trí tuệ không rời tay, cung thiền định nằm sẵn bên vai, vừa có bóng dáng kẻ thù xuất hiện, chúng ta liền hành động ngay. Bất cứ lúc nào, nơi nào cũng là bãi chiến trường, chúng ta sẵn sàng ứng chiến hai mươi bốn trên hai mươi bốn *(24/24)*. Có vậy, trận chiến với ma phiền não mới thành công viên mãn. Bởi chúng là ma, nên sự ẩn hiện của chúng khó lường, chúng ta luôn đề cao cảnh giác không một phút giây lơi lỏng, mới mong có ngày *"ca khúc khải hoàn"*.
