# Nước có dậy sóng không? {- #nuoc-co-day-song-khong}

Mùa đông năm 1991, tôi ra Vũng Tàu dưỡng bệnh, ở nhờ thất Thích Ca của Quan Âm Phật Ðài. Trước cửa thất nhìn xuống mặt biển có cây Bồ đề sum sê che rợp, râm mát cả thất. Tôi thường ra đứng dưới tàng cây nhìn xuống biển. Một hôm, tôi đứng nhìn ra biển thấy biển cả thênh thang sóng bủa trắng xóa, lúc đó có chú thị giả đứng bên cạnh, nhìn sang chú tôi hỏi: *"Ðố chú nước có dậy sóng không?"*. Chú ngần ngại thưa: *"Có"*. Tôi hỏi tiếp: *"Nước có chảy không?"*. Chú thưa: *"Có"*. Tôi chậm rãi bảo chú: "*Nếu nước dậy sóng và chảy thì khi không gió, hoặc nước chứa trong hồ sao không tự dậy sóng và chảy?"*. Chú thị giả lặng câm. Nhân đây tôi giải thích rộng cho chú hiểu:

Nước không dậy sóng và không chảy. Nếu nước hay dậy sóng và chảy thì bất cứ lúc nào, ở đâu nước cũng dậy sóng và chảy, vì bản chất nó là như thế. Như con người chúng ta là động thì bất cứ lúc nào, ở đâu đều là động, dù cho khi ngủ yên mũi vẫn thở, tim vẫn đập, máu vẫn tuần hoàn, nếu dừng động là con người chết. Song nước không phải thế, bản chất nước là yên lặng, khi bị gió đùa hoặc bị một tác động nào khác, như tàu chạy... nước mới dậy sóng. Chúng ta chứa nước trong hồ, trong vò, khạp... thì nước yên lặng, mặc dù nước vừa múc trên lượn sóng đang vỗ ầm ầm, mà chứa vào chỗ an tịnh nước từ từ lặng yên. Nước cũng không chảy, nếu nước bản chất hay chảy thì lúc nào và ở đâu nước cũng phải chảy. Thực tế chúng ta thấy không phải thế, nước có khi chảy có khi dừng, ở chỗ này chảy, ở chỗ khác không chảy. Chẳng qua nước là thể lỏng, ở chỗ cao thì nước chảy dồn xuống chỗ thấp, hoặc bị sức ép hay sức hút thì nước liền di chuyển, nếu ở chỗ bình, trong hoàn cảnh bình thường thì nước an nhiên bất động. Tôi có thể kết luận rằng:

*"Nước dậy sóng và chảy là do duyên"*. Cái gì làm duyên khiến nước dậy sóng? - Gió là duyên chủ yếu khiến nước dậy sóng. Bởi duyên gió thổi mặt nước dậy sóng, gió càng mạnh thì sóng càng to. Khi sóng đang bủa ầm ầm thì có trăm ngàn lượn khác nhau, luợn A không phải lượn B... Bấy giờ có danh từ Sóng và Nước dường như hai, mà thực thể sóng với nước không phải hai. Sóng là tướng động của nước, khi tướng động dừng, chỉ còn lại một thể nước an tịnh. Ðứng về mặt sóng thì có trăm ngàn thứ, đứng về mặt nước thì không có hai. Chính sóng tức là nước, rời nước không có sóng. Người thông minh muốn cần nước cứ trên sóng mà lấy, cần thấy mặt biển phẳng lặng chỉ chờ khi sóng dừng thì thấy. Nếu bỏ sóng đi tìm nước là người ngu, chạy tìm mặt biển phẳng lặng ngoài chỗ sóng dậy ầm ầm là kẻ dại. Bám trên từng lượn sóng cho là mặt biển là kẻ đại ngu. Phải biết vô số lượn sóng rượt đuổi nhau la hét ì ầm trên mặt biển là tướng sanh diệt, chính mặt biển bát ngát thênh thang này mới là thể bất diệt bất sanh.

Này chú! Nơi tôi và chú sẵn có tâm thể thênh thang an tịnh dụ như mặt biển, vọng tưởng dấy khởi dụ như dậy sóng. Một lượn sóng nổi lên trên mặt biển, muôn ngàn lượn sóng tiếp nối dấy lên; cũng thế một vọng tưởng khởi dậy, muôn ngàn vọng tưởng tiếp nối khởi lên. Chúng ta nhìn trên mặt biển thấy những lượn sóng hùng hổ rượt đuổi ầm ầm trùng điệp, tưởng chừng như mặt biển chỉ có sóng với sóng. Nội tâm chúng ta khi vọng tưởng nổi lên ào ạt liên miên, tưởng như nội tâm mình chỉ là vọng tưởng. Do đó, hầu hết người đời đều chấp nhận vọng tưởng là tâm của mình. Ðến khi gió yên sóng lặng, chúng ta mới biết sóng chỉ là tướng sanh diệt tạm thời trên mặt biển, duy mặt biển mới là thể chân thật bất diệt bất sanh. Nội tâm được những giây phút an tịnh, chúng ta mới biết vọng tưởng là tướng sanh diệt hư dối trong tâm thể, chỉ có tâm thể mới là thể bất diệt bất sanh. Vọng tưởng có khi có, có khi không, tâm thể hằng hữu chưa lúc nào vắng mặt. Chấp nhận vọng tưởng là tâm mình, khác gì người chấp sóng là mặt biển.  

Trong kinh Lăng Nghiêm đức Phật kể: Thuở xưa có anh chàng tên Diễn-nhã-đạt-đa sáng sớm lấy gương soi mặt, thấy đầu mặt hiện rõ ràng trong gương, khi úp gương lại không còn thấy đầu mặt đâu nữa, chàng ta phát điên ôm đầu chạy la to: *"Tôi mất đầu! Tôi mất đầu!"*. Chú biết đức Phật kể câu chuyện này cốt nói điều gì không? - Dạ không. Ðây là đức Phật ám chỉ người nhận vọng tưởng làm tâm mình, như chàng Diễn-nhã nhận bóng trong gương làm đầu mặt mình thật, khi mất bóng, phát điên ôm đầu thật chạy kêu mình mất đầu. Mặt biển nguyên không hai, vừa có lượn sóng dấy động biến thành hai, vì đã có biển và sóng. Cho nên các Thiền sư qua một câu hỏi hoặc đáp thấy Thiền khách suy nghĩ liền đưa hai ngón tay. Song sóng không đơn thuần chỉ dấy một lượn, mà lượn này vừa khởi trăm ngàn lượn khác nối tiếp theo *(nhất ba tài động vạn ba tùy)*. Vọng tưởng cũng vậy, một niệm khởi lên trăm ngàn vọng tưởng tiếp nối. Người tu không ngừa đón được niệm đầu thì không tài nào ngăn chận được những niệm sau. Sóng có khi dấy có khi lặng, mặt biển chưa bao giờ vắng mặt. Vọng tưởng lúc có lúc không ,tâm thể khi nào cũng hiện hữu. Sóng có thể tìm cách ngăn chận được, còn mặt biển chú thử có cách nào xua đuổi được nó hay không? Người tu có thể xả bỏ vọng tưởng, chớ không ai xa rời tâm thể được. Chú thử nghĩ, người ta xả bỏ vọng tưởng để tâm thể hiện bày trọn vẹn, hoặc xả bỏ tâm thể để vọng tưởng hiện lên đầy đủ, hai cách đó cách nào khó, cách nào dễ? Thưa: Bỏ vọng tưởng dễ, chớ tâm thể làm sao bỏ được. Ðấy! Vậy mà có nhiều người tu nói *"bỏ vọng tưởng khó"*. Bỏ cái sanh diệt, bảo tồn cái bất sanh bất diệt là vô sanh, là giải thoát. Trái lại, quên cái bất sanh bất diệt, chạy theo cái sanh diệt là sanh tử, là trầm luân. Biển yên tịnh là sự thái bình của người và vật, biển động sóng to là sự hiểm nguy cho người và vật. Tâm thể thanh tịnh là hạnh phúc, là Niết-bàn của con người; tâm thể dấy động là phiền não, là trần lao của nhân loại. Phật dạy rất nhiều pháp tu, chủ yếu không ngoài dạy chúng ta *"đừng chạy theo vọng tưởng, phải nhận chân tâm thể hiện tiền"*. Chạy theo vọng tưởng là mê, nhận chân tâm thể hiện tiền là giác. Mê là quên tâm thể nhận vọng tưởng, giác là bỏ vọng tưởng nhận tâm thể. Bởi con người đã mê, nên Phật dùng nhiều phương tiện chỉ dạy trừ dẹp vọng tưởng: Trực tiếp biết rõ vọng tưởng không theo; gián tiếp dùng niệm khác đè ép, như trì danh hiệu Phật, trì câu thần chú, khán thoại đầu... Khi nhiếp phục vọng tưởng được yên lặng, chỉ còn tâm thể thường hằng, gọi là kiến tánh, ngộ đạo, nhất tâm...

Gió dụ cho pháp trần. - Gió là tác nhân chủ yếu khiến mặt biển dậy sóng. Pháp trần là tác nhân chủ yếu khiến tâm thể dấy khởi vọng tưởng. Nhưng nói pháp trần chắc chú không biết là cái gì? Sách Phật thường nói: *"Sáu căn tiếp xúc với sáu trần sanh sáu thức"*. Ðây tôi chỉ giải riêng sáu trần, chỗ chú trọng đặc biệt là pháp trần. Sáu trần là: sắc, thanh, hương, vị, xúc, pháp. Sắc là tất cả hình sắc do mắt thấy được, thanh là mọi thứ âm thanh do tai nghe, hương là các thứ mùi thơm hoặc hôi do mũi tiếp xúc, vị là các chất vị ngon dở mặn lạt... do lưỡi cảm nhận, xúc là xúc chạm có cảm giác thích thú hay bực bội nơi thân, pháp là bóng dáng của năm thứ trước còn rơi rớt trong tâm thức. Sáu thứ này đều có hình tướng hoặc thô hoặc tế, là tướng biến động vô thường nên gọi là trần. Riêng pháp trần không tự có, do năm căn *(mắt, tai, mũi, lưỡi, thân)* tiếp xúc với năm trần có cảm giác thích thú hay bực bội kích thích mạnh mà sanh ra. Như mắt thấy sắc đẹp có sức quyến rũ say mê hoặc thấy hình tướng kỳ quái ghê rợn thì ấn tượng sắc trần ấy in sâu trong tâm thức khiến chúng ta nhớ mãi. Tai nghe lời tán tụng ngợi khen mình, hoặc lời chỉ trích cay nghiệt ta thì ấn tượng thanh trần ghi sâu trong tâm thức khiến ta khó quên được. Mũi ngửi mùi thơm đặc biệt hoặc mùi hôi khó thở, thì ấn tượng hương trần in sâu trong tâm thức ta rồi. Lưỡi thưởng thức vị ngon khoái khẩu hoặc vị cay đắng tái tê thì ấn tượng vị trần đã ghi đậm nét trong tâm thức chúng ta. Thân xúc chạm những vật có cảm giác thỏa mãn hoặc cảm giác đau khổ thì ấn tượng xúc trần đã rơi rớt vào kho tâm thức mình rồi. Những thứ bóng dáng của năm trần lưu trữ trong kho tâm thức, đợi khi năm căn không tiếp xúc với hiện cảnh thì chúng ào ạt dấy khởi, gọi là pháp trần. Pháp trần vừa dấy lên thì ý thức duyên theo phân biệt, nên nói ý thức duyên pháp trần. Ý thức chạy theo pháp trần là bám chặt bóng dáng hư ảo, đuổi theo cái sanh diệt hư ảo là sanh tử luân hồi. Chú thấy nguy hiểm không? Thế mà người đời cứ săn đuổi tìm kiếm năm trần để làm thỏa mãn năm căn. Giả sử năm căn được thỏa mãn, con người có an lành miên viễn không? Khao khát ước mơ thụ hưởng năm trần là dồn chứa pháp trần vào tâm thức, thử hỏi kho tàng thức của họ có tràn trề pháp trần không? Vì thế khi họ ngồi yên tọa thiền hay niệm Phật, vọng tưởng vọt lên ào ào không cách nào ngăn đón được, họ than tu hành khó quá. Nếu người nào trong tâm thức trống sạch pháp trần thì con khỉ ý thức không còn cơ hội chạy nhảy. Ý thức là vọng tưởng, là những mảnh vụn của tâm thể, là những áng mây đen che mờ mặt trăng tuệ giác, là những lượn sóng dấy động trên mặt biển chân tâm thanh tịnh của chúng ta. Bản thân ý thức tự không có, do pháp trần khuấy động nảy sanh ý thức duyên theo. Do đó, người tu gắng sức đè dẹp ý thức là không hợp lý, cốt đừng dung chứa pháp trần là yên. Nếu pháp trần đã chứa, phải khéo léo loại bỏ, đồng thời không nuôi dưỡng chúng. Ðức Phật dạy rất nhiều phương tiện ngăn đón và loại bỏ pháp trần. Cụ thể những phương tiện sau đây:

- **Răn cấm để ngừa đón pháp trần.**  
Phật cấm người xuất gia không được nhìn xem với vẻ trìu mến sắc đẹp người và vật, cốt ngừa đón nhãn căn tiếp xúc sắc trần không cho sanh pháp trần rơi trong tâm thức. Người xuất gia không được nghe âm nhạc tình tứ lãng mạn, ngừa đón nhĩ căn tiếp xúc thanh trần không cho sanh pháp trần. Người xuất gia không được dùng các thứ dầu thơm, ngừa đón tỷ căn tiếp xúc hương trần không sanh pháp trần. Người xuất gia không được ăn thịt uống rượu và đòi các món ngon khác, ngừa đón thiệt căn tiếp xúc vị trần không sanh pháp trần. Người xuất gia không được dâm dục và nằm ngồi giường ghế êm đẹp, ngừa đón thân căn tiếp xúc xúc trần không sanh pháp trần... Ðây là đức Phật dùng giới luật làm phương tiện ban đầu để ngừa đón không cho sanh pháp trần lưu trữ trong tâm thức.

- **Dùng trí tuệ quán sát.**  
Con người do chấp thân, tâm, cảnh là thật nên suốt ngày quay cuồng vì ba thứ này, tạo ra vô số chủng tử pháp trần lưu trữ trong tàng thức. Người tu Phật phải vận dụng trí tuệ quán chiếu căn trần thức đều do nhân duyên hòa hợp mà có, không thực thể. Căn là thân, trần là cảnh, thức là tâm, cả ba đều do nhân duyên hội tụ mà thành, cũng do ba thứ này duyên nhau tạo thành nhân sinh vũ trụ. Như thế, nhân sinh vũ trụ đều là tướng duyên hợp không có chủ thể, đủ duyên thì thành, thiếu duyên thì hoại, hư dối không thật như huyễn như hóa. Quán chiếu thuần thục thấy ba thứ ấy quả thực không thật, thì sự xúc chạm thành hoại đến đi của chúng không còn gì phải bận tâm ta, tức là không còn duyên cớ để sanh ra pháp trần. Ðây là dùng trí tuệ của chính mình để quán chiếu phá tan mọi chủng tử pháp trần.

- **Nhận ra chân tâm hằng hữu.**  
Nơi mỗi chúng ta đều có tâm thể chân thật hằng hữu. Vì quên nó, chúng ta cố chấp thân này là thật, chạy theo sự đòi hỏi của năm căn *(mắt, tai, mũi, lưỡi, thân)* muốn được thụ hưởng thỏa mãn đối với năm trần *(sắc, thanh, hương, vị, xúc)*, dấy lên sự so sánh phân biệt của năm trần là năm thức (*nhãn thức, nhĩ thức, tỹ thức, thiệt thức, thân thức)*, do chú tâm phân biệt tạo nên pháp trần rơi vào tàng thức. Pháp trần đã lưu trữ trong tàng thức, nên khi dấy khởi liền có ý thức duyên theo, tức là thành sáu căn, sáu trần và sáu thức. Thấy thân thật thì căn trần thức đều thật. Do nhận ra tâm thể chân thật hằng hữu mới thực là mình, người này liền biết thân do tứ đại hòa hợp là hư giả. Thấy thân giả thì căn trần thức đều giả, tự nhiên chúng ta sẽ dửng dưng không dính mắc với sáu trần. Nhà Thiền nói: *"Thấy sắc như đui, nghe tiếng như điếc",* hoặc nói *"căn trần không dính nhau là giải thoát"*. Ðến đây không dùng phương tiện ngừa đón hay dùng trí tuệ quán sát, chỉ nhớ tâm chân thật hiện hữu thì mọi thứ hư dối đều dừng.

Cao thấp, sức ép, sức hút nước chảy dụ năm trần.- Năm căn chúng ta có sẵn tính luyến ái năm trần, khi tiếp xúc với trần nào đúng sở thích của nó liền bị sức hút lôi cuốn. Như mắt thấy sắc đẹp bị sức hấp dẫn nó liền chạy theo đuổi bắt, bị sắc trần lôi cuốn. Tai nghe tiếng hay say mê đòi được thỏa mãn lỗ tai, tìm mọi cách gần gũi, bị thanh trần chi phối. Mũi ngửi mùi thơm say đắm dùng trăm phương ngàn kế để được ngửi mãi, bị hương trần trói buộc. Lưỡi nếm vị ngon thích khẩu tham mê đòi hỏi thường được thưởng thức, dùng mọi thủ đoạn tranh giành để thỏa mãn cái lưỡi, bị vị trần làm chủ. Thân xúc chạm vật có cảm giác hấp dẫn đam mê, dùng mọi thủ thuật chiếm hữu bất kể trước mắt có những hiểm nguy, bị xúc trần xỏ mũi.

Chận đón năm căn khỏi bị năm trần lôi cuốn.

- **Quán các cảm thọ vô thường.**  
Con người thường bị cảm giác khổ vui làm chủ, khi mắt thấy sắc đẹp vừa ý liền bị cảm giác thọ vui thu hút. Chúng ta phải quán sát cái cảm giác thọ vui vừa có, liền qua mất không lâu bền. Các cảm giác thọ vui của tai, mũi, lưỡi, thân cũng thảy đều vô thường, vừa cảm nhận thụ hưởng thích thú trong giây phút liền mất, nếu còn chỉ là dư vị trong tưởng tượng mà thôi. Theo đuổi những thú vui tạm bợ mỏng manh ấy, thật là hoài công của một kiếp người. Nhận chân lẽ thật này, chúng ta sẽ làm chủ được mình không bị năm trần lôi kéo.

- **Quán các cảm thọ hư dối.**  
Những cảm thọ khổ vui của năm căn vốn không tự có, đợi sự tiếp xúc giữa căn và trần mới nảy sanh. Phàm vật gì đợi duyên hợp mới có là không tự thể. Cảm thọ khổ vui đã không tự thể làm sao thật được. Do duyên hợp mà có, duyên tan liền mất, cái có ấy như trò ảo thuật, như giấc chiêm bao, chúng ta quan tâm làm gì? Con người là thông minh hơn muôn vật chẳng lẽ chúng ta nỡ thả trôi suốt đời mình theo cái ảo hóa ấy sao? Song thật đáng thương, con người cả đời say mê đắm đuối theo cái cảm thọ vui của năm căn này. Giành giựt nhau thụ hưởng, sát phạt nhau để được phần hơn, trù rủa, xâu xé, oán hờn, thù hận... chỉ vì thụ hưởng vui của năm căn mà ra. Chúng ta mang chiếc thân tạm bợ có mấy mươi năm đành cam vùi dập nó trong cái chùm ảo hóa, xô đẩy lôi kéo nhau xuống hồ sâu huyết lệ thương đau. Sao chúng ta không thức tỉnh, để an ủi nhau, đùm bọc nhau, che chở nhau, giúp đỡ nhau cho vơi bớt khổ đau trong cuộc đời hư ảo tạm bợ này?

Này chú! Tôi đã nói khá nhiều e chú không thể nhớ nổi, giờ đây tôi thu gọn lại cho chú dễ nhớ. Nước biển dụ tâm thể hay chân tâm. Sóng dụ vọng tưởng. Gió dụ pháp trần. Chỗ cao thấp, sức ép, sức hút dụ năm trần. Nước vốn không dậy sóng, không chảy để dụ tâm thể hằng hữu bất động. Song khi gió thổi đùa nước, sóng liền nổi dậy để dụ pháp trần lưu trữ trong tàng thức khi gặp duyên dấy lên, ý thức liền duyên theo tạo thành vọng tưởng lăng xăng. Nước là thể lỏng tự an tịnh, gặp duyên cao thấp, sức ép, sức hút liền di chuyển từ chỗ này đến chỗ khác biến thành nước chảy, để dụ tâm thể tự an tịnh bị sức lôi cuốn thu hút của năm trần khiến năm thức trôi lăn theo rồi dính mắc. Chúng ta tu theo Phật không sợ vọng tưởng, không ngại năm trần *(ngũ dục)*, chỉ cần khôn ngoan khi căn trần tiếp xúc nhau đừng để dính mắc và tạo ra pháp trần gieo vào tàng thức. Không dính mắc là giải thoát, không có pháp trần là tâm thể thanh tịnh. Giải thoát và thanh tịnh là mục tiêu tối hậu của người tu Phật. Muốn đạt được mục đích này, chú phải khéo ngăn ngừa rào đón khi căn trần tiếp xúc nhau sanh cảm thọ khổ vui, biết rõ các cảm thọ này là tạm bợ hư ảo, là nhân trầm luân đau khổ; không thèm thuồng, không hưởng thụ, không say đắm, mà dửng dưng trước mọi cám dỗ và thách đố của chúng. Ðược vậy, bảo đảm chú sẽ thành công trên đường học đạo.


