# Nụ cười bất diệt {- #nu-cuoi-bat-diet}

Trong thời gian yên tu, một hôm bỗng dưng chúng tôi cảm thông được nụ cười nhẹ nhàng hiện trên môi tượng đức Phật và nụ cười tạm biệt của các Thiền sư khi từ giã cuộc đời. Tại sao bài thuyết pháp đầu tiên của đức Phật tại Lộc Uyển đề cập trước nhất là Khổ đế, cho đến nhiều bài thuyết pháp sau này, đức Phật cũng thường nhắc đến nỗi khổ của chúng sanh vô tận bằng những câu *"nước mắt chúng sanh nhiều hơn nước biển cả..."*, mà trên gương mặt Ngài luôn nở nụ cười?
 
Vô minh là cội nguồn của muôn kiếp khổ đau. Con người có mặt trên cõi đời do vô minh chủ động, nên khi ra đời đã mang sẵn chất keo đau khổ. Vô minh là gì mà đày đọa con người lắm thế? - Vô minh là nhận hiểu sai lầm về con người và muôn vật. Về con người, thân này là cái không thể giữ mà cố giữ, cái sắp bại hoại mà muốn không bại hoại, cái tạm bợ mà tưởng lâu dài, cái nhơ nhớp mà tưởng đẹp đẽ; các cảm giác là hư ảo mà tưởng là chân thật, cảm giác là vô thường mà tưởng lâu dài, cảm giác là đau khổ mà tưởng là hạnh phúc; nội tâm vọng tưởng là ảo ảnh mà chấp là tâm mình, chân tâm bất diệt thì lơ là không biết đến. Về muôn vật, những sắc hình hào nhoáng, những âm thanh sanh diệt, những hương vị tạm bợ, mà mê say đắm đuối, khao khát thèm thuồng đuổi bắt suốt đời không biết mệt mỏi. Từ những nhận hiểu sai lầm này, con người không bao giờ toại nguyện, không bao giờ được như ý, không bao giờ thấy hạnh phúc; mà luôn luôn thấy bất mãn, bất như ý, bất hạnh... là nguồn gốc khổ đau. Cái nhận hiểu sai lầm này gắn chặt vào chúng ta từ đời này sang kiếp nọ, mãi mãi không rời, cho nên khổ đau do nó gây ra không biết lấy đâu làm ngằn mé, chỉ còn cách diễn tả *"nước mắt chúng sanh nhiều hơn nước biển cả"*.

Mặc dù vô minh hiểm nguy như thế, song một phen giác ngộ chúng liền tiêu tan. Như ngôi nhà tối ngàn năm chỉ cần thắp ngọn đèn sáng lên thì bóng tối tan mất. Cái mê lầm u tối tạo thành muôn ngàn sợi dây nghiệp khổ, trói buộc lôi kéo con người lăn lộn trong vạn nẻo luân hồi, tưởng chừng như không có cách gì thoát khỏi; đâu ngờ ngọn đèn giác ngộ vừa bừng sáng lên, chúng liền lui mất không còn tung tích. Thấy tường tận sự việc này, đức Phật không nở nụ cười an lành sao được.

Chúng sanh si mê tranh giành sắc, tài, danh, lợi, đấm đá nhau, sát phạt nhau, lừa đảo nhau, hận thù nhau... biến cảnh nhân gian trở thành bãi chiến trường. Kẻ thắng thì được hoan hô thăng thưởng, được vật chất dẫy đầy; người bại thì bị khinh miệt chê đè, bị thân tàn nghèo đói. Một bên hạnh phúc, một bên khổ đau hiện bày trước mắt mọi người. Vì thế, bất cứ ai có mặt trên trần gian đều sẵn sàng cầm kiếm xông vào trận mạc để mong giành phần thắng về mình. Nhưng nơi chiến trường đâu phải ai cũng là kẻ thắng. Có người thắng là có kẻ bại, có hạnh phúc là có khổ đau. Ðôi khi kẻ bại phải tan thân mất mạng đã đành, mà người thắng cũng thương tích đầy mình. Hạnh phúc rất ít mà khổ đau quá nhiều. Mặc dầu là thế, ở đời có ai chịu nhường bước cho ai. Những chiếc xe tranh nhau qua mặt gây tai nạn, hằng ngày xảy ra nhan nhản trước mắt, mà các chú tài xế ít khi chịu nhường tránh nhau để mình và người được sự an toàn. Tranh đấu đã trở thành qui luật của con người. Song kẻ thắng người bại kết cuộc sẽ thành cái gì? - Một nấm mồ hay một nhúm tro tàn!

Ðời người là diễn viên đang diễn xuất những vở bi hài kịch trên sân khấu của kịch trường. Dù đóng vai người tài danh lỗi lạc hay đóng vai kẻ ăn mày cùng khổ ở xó chợ đầu đường, khi hạ màn kết thúc thì mọi việc đều không. Trong lúc giả trang tạm thời ấy, mọi sự được mất thành bại... đều là trò chơi. Người diễn viên thông minh đóng kịch, dù bi kịch hay hài kịch, khi sân khấu buông màn liền nở nụ cười, đây là trò đùa trên sân khấu, không có một chút hối tiếc hay lo buồn. Ðức Phật đã giác ngộ viên mãn, thấy rõ cuộc đời là vô thường ảo hóa, khi từ giã cuộc đời tự nhiên Ngài hé môi cười nhẹ.

Những thứ suy tư nghĩ tưởng trong nội tâm, mỗi con người chúng ta đều thừa nhận là tâm của mình, hoặc nhận là mình. Tôi suy tư thế này, tôi nghĩ tưởng thế kia, hoặc tôi nghĩ tôi tưởng. Do thừa nhận chúng là mình, nên chúng ra oai tác quái tạo đủ thứ nghiệp, cột trói lôi kéo mình lăn tròn trong lục đạo không có ngày thoát khỏi. Hằng ngày các thứ ấy lăng xăng lộn xộn bủa vây che đậy trong nội tâm chúng ta không một phút giây an ổn. Có khi chúng nó ồn ào náo loạn khiến đầu óc ta nóng rực bất an, cố van xin chúng cho ta được vài phút an lành, nhưng chúng nó nào có chịu tha, cứ tha hồ quậy, buộc lòng ta phải dùng thuốc an thần để kháng cự. Thậm chí những nhà tu hành cũng bực bội sự náo loạn của chúng, phải chạy tìm cầu *"pháp an tâm"*. Có vị sợ sự trói buộc vô hạn định của chúng, phải đi cầu xin *"pháp giải thoát"*. Gặp bậc thầy cỡ lớn, nhà tu hành liền đem ra hỏi *"pháp an tâm"*. Ông thầy nghiêm nghị bảo *"đem tâm ra ta an cho"*. Nhà tu hành sửng sốt phản quang soi lại thì bọn giặc ồn ào đã biến đâu mất, đành thưa *"con tìm tâm không được"*. Bậc thầy nhếch mép cười bảo *"ta đã an tâm cho ngươi rồi"*. Nhà tu hành bỗng dưng thấy bọn giặc ấy là một đám khói mây. Nhà tu hành khác thao thức lo sợ sự trói buộc của đám phiền não này, đi cầu thầy dạy *"pháp giải thoát"*. Ông thầy cỡ lớn chỉ hỏi *"ai trói buộc ông"*. Nhà tu hành tìm lại không thấy có gì trói buộc, liền thưa *"không có ai trói buộc"*. Ông thầy cả cười bảo *"cầu giải thoát làm gì?"*. Nhà tu hành bỗng dưng thấy trăm dây ngàn mối trước kia nhất thời đã biến đâu mất.

Khi thấy tột bản chất ảo hóa của các thứ tâm lăng xăng lộn xộn này, đức Phật chỉ còn cười với chúng mà thôi! Nếu ai còn lầm nhận chúng là mình thì bị chúng ra oai tác quái; trái lại người biết rõ bản chất hư ảo của chúng thì không bị chúng lừa gạt và khả năng lôi kéo của chúng cũng bị hạn chế. Thấy rõ các thứ tâm hư ảo rồi, đức Phật còn nhận ra tâm thể chân thật nơi mỗi con người là thênh thang trùm khắp, chưa bao giờ bị sanh diệt vô thường. Xả bỏ thân khổ đau nhớp nhúa, tạm bợ, thể nhập pháp thân thanh tịnh bất sanh bất diệt *(Niết-bàn)*, nhẹ nhàng an lạc biết mấy, thì làm sao đức Phật chẳng hé nở nụ cười an lành thanh thản. Không những Phật, mà các Thiền sư đệ tử Phật khi từ giã cuộc đời cũng cười. Tôn giả Pháp Loa khi sắp tịch để kệ:

Dịch âm:

<div class="align-center">
Vạn duyên tài đoạn nhất thân nhàn,  
Tứ thập dư niên mộng huyễn gian.  
Trân trọng chư nhân hưu tá vấn,  
Na biên phong nguyệt cánh man khoan.  
</div>

Dịch nghĩa:  

<div class="align-center">
Muôn duyên cắt đứt một thân nhàn,  
Hơn bốn muơi năm giấc mộng tràng.  
Nhắn bảo mọi người thôi chớ hỏi,  
Bên kia trăng gió rộng thênh thang.  
</div>

Ðeo mang thân này là đeo mang gông cùm, bệnh tật, bại hoại, khổ đau, buông xả được nó thì nhẹ nhàng thảnh thơi an lạc. Xả bỏ thân này đâu phải là hết, mà còn bầu trời mênh mông có trăng trong gió mát, còn gì thích thú bằng nên Thiền sư cười!

Người thế gian có khi cười có lúc khóc, hoặc cười xã giao, cười nhạo báng, cười gằn, cười gượng khóc thầm..., tất cả cái cười ấy đều thuộc về tình cảm sanh diệt. Cái cười của đức Phật, của Thiền sư là nụ cười giác ngộ thoát ra ngoài mọi thứ mê lầm, chỉ có cười mà không có khóc, gọi là *"nụ cười bất diệt"*. Hơn nữa, vì đạt được thể vô sanh, mọi khổ đau sanh diệt đã trút sạch, thong dong tự tại đi trên con đường Niết- bàn, trên môi nở nụ cười rạng rỡ, nụ cười này thật là *"nụ cười bất diệt"*. Như thế, có ai cả gan dám lớn tiếng bảo đạo Phật là bi quan. Ðạo Phật tạo cho con người niềm vui hiện tại và mãi đến mai sau. Chúng ta tu theo đạo Phật là vứt bỏ mê lầm để cho đời này được an lạc và giác ngộ để về sau mãi mãi an lạc. Chính đây là mục đích cứu khổ của đạo Phật. Ðạo cứu khổ cho chúng sanh, quả là đạo ban vui. Vì hết khổ là được vui, nên phải nói đạo Phật thực sự là lạc quan, mà là lạc quan vĩnh cửu.  
